from dataclasses import dataclass

from rtt.app.spreadsheet_constants import SYMBOL_HEIGHT, UNIT_HEIGHT

NORM_SUB_OPEN = chr(0xE001)
NORM_SUB_CLOSE = chr(0xE002)
SUB_OPEN = chr(0xE003)
SUB_CLOSE = chr(0xE004)
SUBSCRIPT_L = SUB_OPEN + "L" + SUB_CLOSE
SUBSCRIPT_J = SUB_OPEN + "j" + SUB_CLOSE
SUBSCRIPT_C = SUB_OPEN + "C" + SUB_CLOSE

COUNTS = (
    ("generators", "r", "rank"),
    ("primes", "d", "dimensionality"),
    ("commas", "n", "nullity"),
    ("targets", "k", "target interval count"),
)
COUNTS_TILES = tuple((f"block:counts:{column_key}", "counts", column_key) for column_key, *_ in COUNTS)

OPTIMIZATION_COUNTS = (("held", "h", "held interval count"),)
OPTIMIZATION_COUNTS_TILES = tuple(
    (f"block:counts:{column_key}", "counts", column_key) for column_key, *_ in OPTIMIZATION_COUNTS
)
DETEMPERING_COUNTS = (("detempering", "r", "rank"),)
DETEMPERING_COUNTS_TILES = tuple(
    (f"block:counts:{column_key}", "counts", column_key) for column_key, *_ in DETEMPERING_COUNTS
)

SUPERSPACE_COUNTS = (
    ("superspace_generators", "rL", "superspace rank"),
    ("superspace_primes", "dL", "superspace dimensionality"),
)
SUPERSPACE_COUNTS_TILES = tuple(
    (f"block:counts:{column_key}", "counts", column_key) for column_key, *_ in SUPERSPACE_COUNTS
)

CAPTIONS = {
    ("superspace_vectors", "superspace_primes"): "superspace JI mapping",
    ("superspace_vectors", "primes"): "basis change matrix",
    ("superspace_vectors", "commas"): "comma basis in superspace",
    ("superspace_vectors", "held"): "held interval basis in superspace",
    ("superspace_vectors", "targets"): "target interval list in superspace",
    ("superspace_vectors", "interest"): "intervals in superspace",
    ("superspace_vectors", "detempering"): "generator detempering in superspace",
    ("superspace_mapping", "superspace_generators"): "superspace mapped generators",
    ("superspace_mapping", "superspace_primes"): "superspace mapping",
    ("superspace_mapping", "primes"): "mapping from domain intervals to superspace generators",
    ("superspace_mapping", "commas"): "comma basis in superspace generators",
    ("superspace_mapping", "held"): "held interval basis in superspace generators",
    ("superspace_mapping", "targets"): "target interval list in superspace generators",
    ("superspace_mapping", "interest"): "intervals in superspace generators",
    ("superspace_mapping", "detempering"): "generator detempering in superspace generators",
    ("superspace_projection", "superspace_primes"): "superspace projection",
    ("superspace_projection", "superspace_generators"): "superspace generator embedding",
    ("superspace_projection", "primes"): "superspace projected subspace basis elements",
    ("superspace_projection", "detempering"): "projected generator detempering in superspace",
    ("superspace_projection", "commas"): "projected comma basis in superspace",
    ("superspace_projection", "targets"): "projected target interval list in superspace",
    ("superspace_projection", "held"): "projected held interval basis in superspace",
    ("superspace_projection", "interest"): "projected intervals in superspace",
    ("tuning", "superspace_generators"): "superspace generator tuning map",
    ("tuning", "superspace_primes"): "superspace tuning map",
    ("just", "superspace_primes"): "superspace just tuning map",
    ("retune", "superspace_primes"): "superspace retuning map",
    ("vectors", "commas"): "comma basis",
    ("vectors", "targets"): "target interval list",
    ("canonical", "generators"): "inverse generator form matrix",
    ("canonical", "canonical_generators"): "form matrices canceling out",
    ("canonical", "primes"): "canonical mapping",
    ("mapping", "canonical_generators"): "generator form matrix",
    ("projection", "canonical_generators"): "canonical generator embedding",
    ("tuning", "canonical_generators"): "canonical generator tuning map",
    ("canonical", "detempering"): "canonically mapped generator detempering",
    ("canonical", "commas"): "canonically mapped comma basis (made to vanish!)",
    ("canonical", "held"): "canonically mapped held interval basis",
    ("canonical", "targets"): "canonically mapped target interval list",
    ("canonical", "interest"): "canonically mapped intervals",
    ("vectors", "held"): "held interval basis",
    ("vectors", "detempering"): "generator detempering",
    ("vectors", "primes"): "JI mapping",
    ("mapping", "primes"): "(temperament) mapping",
    ("mapping", "generators"): "mapped generators",
    ("mapping", "detempering"): "mapped generator detempering",
    ("mapping", "commas"): "mapped comma basis (made to vanish!)",
    ("mapping", "targets"): "mapped target interval list",
    ("projection", "primes"): "projection",
    ("projection", "generators"): "generator embedding",
    ("projection", "commas"): "projected unrotated vector list",
    ("projection", "detempering"): "projected generator detempering",
    ("projection", "targets"): "projected target interval list",
    ("projection", "held"): "projected held interval basis",
    ("projection", "interest"): "projected intervals",
    ("projection", "superspace_generators"): "embedding from superspace generators to subspace elements",
    ("projection", "superspace_primes"): "projection from superspace to subspace",
    ("scaling_factors", "commas"): "scaling factor (eigenvalue) list",
    ("tuning", "generators"): "generator tuning map",
    ("tuning", "primes"): "tuning map",
    ("tuning", "commas"): "tempered comma basis interval size list (made to vanish!)",
    ("tuning", "detempering"): "(retempered) generator tuning map",
    ("tuning", "targets"): "tempered target interval size list",
    ("just", "primes"): "just tuning map",
    ("just", "commas"): "(just) comma basis interval size list",
    ("just", "detempering"): "(just) generator detempering interval size list",
    ("just", "targets"): "(just) target interval size list",
    ("retune", "primes"): "retuning map",
    ("retune", "commas"): "comma basis interval retuning list (made to vanish!)",
    ("retune", "detempering"): "generator detempering interval retuning list",
    ("retune", "targets"): "target interval error list",
    ("prescaling", "primes"): "complexity prescaler",
    ("prescaling", "superspace_primes"): "(superspace) complexity prescaler",
    ("prescaling", "commas"): "complexity prescaled comma basis",
    ("prescaling", "detempering"): "complexity prescaled generator detempering",
    ("prescaling", "targets"): "complexity prescaled target interval list",
    ("complexity", "primes"): "domain prime complexity map",
    ("complexity", "superspace_primes"): "domain prime complexity map",
    ("complexity", "commas"): "comma basis interval complexity list",
    ("complexity", "detempering"): "generator detempering complexity list",
    ("complexity", "targets"): "target interval complexity list",
    ("weight", "targets"): "target interval weight list",
    ("damage", "targets"): "target interval damage list",
    **{
        ("counts", column_key): name
        for column_key, _sym, name in COUNTS
        + OPTIMIZATION_COUNTS
        + DETEMPERING_COUNTS
        + SUPERSPACE_COUNTS
    },
    ("vectors", "interest"): "intervals of interest",
    ("mapping", "interest"): "mapped intervals",
    ("tuning", "interest"): "tempered interval sizes",
    ("just", "interest"): "(just) interval sizes",
    ("retune", "interest"): "interval retunings",
    ("prescaling", "interest"): "complexity prescaled intervals",
    ("complexity", "interest"): "interval complexities",
    ("mapping", "held"): "mapped held interval basis",
    ("tuning", "held"): "tempered held interval basis interval size list",
    ("just", "held"): "(just) held interval basis interval size list",
    ("retune", "held"): "held interval basis interval retuning list",
    ("prescaling", "held"): "complexity prescaled held interval basis",
    ("complexity", "held"): "held interval basis interval complexity list",
}
SYMBOLS = {
    ("superspace_vectors", "primes"): "BL",
    ("superspace_mapping", "superspace_primes"): "𝑀L",
    ("tuning", "superspace_generators"): "𝒈L",
    ("tuning", "superspace_primes"): "𝒕L",
    ("just", "superspace_primes"): "𝒋L",
    ("retune", "superspace_primes"): "𝒓L",
    ("superspace_vectors", "superspace_primes"): f"𝑀{SUBSCRIPT_J}{SUBSCRIPT_L}",
    ("superspace_vectors", "commas"): f"C{SUBSCRIPT_L}",
    ("superspace_vectors", "held"): f"H{SUBSCRIPT_L}",
    ("superspace_vectors", "targets"): f"T{SUBSCRIPT_L}",
    ("superspace_vectors", "detempering"): f"D{SUBSCRIPT_L}",
    ("superspace_mapping", "superspace_generators"): f"𝑀{SUBSCRIPT_L}G{SUBSCRIPT_L}",
    ("superspace_mapping", "primes"): f"𝑀ₛ→{SUBSCRIPT_L}",
    ("superspace_mapping", "commas"): f"𝑀ₛ→{SUBSCRIPT_L}C",
    ("superspace_mapping", "held"): f"𝑀ₛ→{SUBSCRIPT_L}H",
    ("superspace_mapping", "targets"): f"Y{SUBSCRIPT_L}",
    ("superspace_mapping", "detempering"): f"𝑀ₛ→{SUBSCRIPT_L}D",
    ("scaling_factors", "commas"): "𝝀",
    ("projection", "commas"): "𝑃V",
    ("projection", "primes"): "𝑃",
    ("projection", "generators"): "G",
    ("projection", "detempering"): "𝑃D",
    ("projection", "targets"): "𝑃T",
    ("projection", "held"): "𝑃H",
    ("projection", "superspace_generators"): f"G{SUBSCRIPT_L}→ₛ",
    ("projection", "superspace_primes"): f"𝑃{SUBSCRIPT_L}→ₛ",
    ("superspace_projection", "superspace_primes"): f"𝑃{SUBSCRIPT_L}",
    ("superspace_projection", "superspace_generators"): f"G{SUBSCRIPT_L}",
    ("superspace_projection", "primes"): f"𝑃{SUBSCRIPT_L}B{SUBSCRIPT_L}",
    ("superspace_projection", "detempering"): f"𝑃{SUBSCRIPT_L}D{SUBSCRIPT_L}",
    ("superspace_projection", "commas"): f"𝑃{SUBSCRIPT_L}C{SUBSCRIPT_L}",
    ("superspace_projection", "targets"): f"𝑃{SUBSCRIPT_L}T{SUBSCRIPT_L}",
    ("superspace_projection", "held"): f"𝑃{SUBSCRIPT_L}H{SUBSCRIPT_L}",
    ("vectors", "commas"): "C",
    ("vectors", "targets"): "T",
    ("vectors", "detempering"): "D",
    ("vectors", "primes"): "𝑀" + SUBSCRIPT_J,
    ("canonical", "primes"): f"𝑀{SUBSCRIPT_C}",
    ("canonical", "generators"): "𝐹⁻¹",
    ("canonical", "detempering"): f"𝑀{SUBSCRIPT_C}D",
    ("canonical", "commas"): f"𝑀{SUBSCRIPT_C}C",
    ("canonical", "held"): f"𝑀{SUBSCRIPT_C}H",
    ("canonical", "targets"): f"Y{SUBSCRIPT_C}",
    ("mapping", "primes"): "𝑀",
    ("canonical", "canonical_generators"): "𝐹⁻¹𝐹",
    ("mapping", "canonical_generators"): "𝐹",
    ("projection", "canonical_generators"): f"G{SUBSCRIPT_C}",
    ("tuning", "canonical_generators"): f"𝒈{SUBSCRIPT_C}",
    ("mapping", "generators"): "𝑀G",
    ("mapping", "detempering"): "𝑀D",
    ("mapping", "commas"): "𝑀C",
    ("mapping", "targets"): "Y",
    ("tuning", "generators"): "𝒈",
    ("tuning", "primes"): "𝒕",
    ("tuning", "commas"): "𝒕C",
    ("tuning", "detempering"): "𝒕D",
    ("tuning", "targets"): "𝐚",
    ("just", "primes"): "𝒋",
    ("just", "commas"): "𝒋C",
    ("just", "detempering"): "𝒋D",
    ("just", "targets"): "𝐨",
    ("retune", "primes"): "𝒓",
    ("retune", "commas"): "𝒓C",
    ("retune", "detempering"): "𝒓D",
    ("retune", "targets"): "𝐞",
    ("prescaling", "primes"): "𝑋",
    ("prescaling", "superspace_primes"): "𝑋",
    ("prescaling", "commas"): "LC",
    ("prescaling", "detempering"): "LD",
    ("prescaling", "targets"): "LT",
    ("prescaling", "held"): "LH",
    ("vectors", "held"): "H",
    ("mapping", "held"): "𝑀H",
    ("tuning", "held"): "𝒕H",
    ("just", "held"): "𝒋H",
    ("retune", "held"): "𝒓H",
    ("complexity", "targets"): "𝒄",
    ("weight", "targets"): "𝒘",
    ("damage", "targets"): "𝐝",
}
ROW_LABEL_LETTERS = {
    ("mapping", "primes"): "𝒎",
    ("canonical", "primes"): f"𝒎{SUBSCRIPT_C}",
    ("mapping", "canonical_generators"): "𝒇",
    ("vectors", "primes"): "𝒎" + SUBSCRIPT_J,
    ("projection", "primes"): "𝒑",
    ("projection", "superspace_primes"): f"𝒑{SUBSCRIPT_L}→ₛ",
    ("prescaling", "primes"): "𝒙",
    ("prescaling", "superspace_primes"): "𝒙",
    ("superspace_mapping", "superspace_primes"): "𝒎L",
    ("superspace_mapping", "primes"): "𝒎ₛ→L",
    ("superspace_vectors", "superspace_primes"): "𝒎" + SUBSCRIPT_J + SUBSCRIPT_L,
    ("superspace_projection", "superspace_primes"): f"𝒑{SUBSCRIPT_L}",
}
COLUMN_LABEL_LETTERS = {
    ("mapping", "detempering"): "𝑀𝐝",
    ("scaling_factors", "commas"): "𝜆",
    ("projection", "commas"): "𝑃𝐯",
    ("projection", "generators"): "𝐠",
    ("projection", "canonical_generators"): f"𝐠{SUBSCRIPT_C}",
    ("tuning", "canonical_generators"): f"𝒈{SUBSCRIPT_C}",
    ("projection", "superspace_generators"): f"𝐠{SUBSCRIPT_L}→ₛ",
    ("projection", "detempering"): "𝑃𝐝",
    ("projection", "targets"): "𝑃𝐭",
    ("projection", "held"): "𝑃𝐡",
    ("projection", "interest"): "𝑃𝐢",
    ("superspace_projection", "superspace_generators"): f"𝐠{SUBSCRIPT_L}",
    ("superspace_projection", "primes"): f"𝑃{SUBSCRIPT_L}𝐛",
    ("superspace_projection", "detempering"): f"𝑃{SUBSCRIPT_L}𝐝",
    ("superspace_projection", "commas"): f"𝑃{SUBSCRIPT_L}𝐜",
    ("superspace_projection", "targets"): f"𝑃{SUBSCRIPT_L}𝐭",
    ("superspace_projection", "held"): f"𝑃{SUBSCRIPT_L}𝐡",
    ("superspace_projection", "interest"): f"𝑃{SUBSCRIPT_L}𝐢",
    ("vectors", "commas"): "𝐜",
    ("vectors", "targets"): "𝐭",
    ("vectors", "held"): "𝐡",
    ("vectors", "detempering"): "𝐝",
    ("superspace_vectors", "primes"): "𝐛",
    ("superspace_vectors", "commas"): f"𝐜{SUBSCRIPT_L}",
    ("superspace_vectors", "held"): f"𝐡{SUBSCRIPT_L}",
    ("superspace_vectors", "targets"): f"𝐭{SUBSCRIPT_L}",
    ("superspace_vectors", "detempering"): f"𝐝{SUBSCRIPT_L}",
    ("superspace_mapping", "commas"): f"𝑀{SUBSCRIPT_L}𝐜",
    ("superspace_mapping", "targets"): f"𝐲{SUBSCRIPT_L}",
    ("superspace_mapping", "held"): f"𝑀{SUBSCRIPT_L}𝐡",
    ("superspace_mapping", "detempering"): f"𝑀{SUBSCRIPT_L}𝐝",
    ("mapping", "commas"): "𝑀𝐜",
    ("mapping", "targets"): "𝐲",
    ("mapping", "held"): "𝑀𝐡",
    ("canonical", "detempering"): f"𝑀{SUBSCRIPT_C}𝐝",
    ("canonical", "commas"): f"𝑀{SUBSCRIPT_C}𝐜",
    ("canonical", "targets"): f"𝐲{SUBSCRIPT_C}",
    ("canonical", "held"): f"𝑀{SUBSCRIPT_C}𝐡",
    ("canonical", "interest"): f"𝑀{SUBSCRIPT_C}𝐢",
    ("tuning", "generators"): "𝒈",
    ("tuning", "primes"): "𝒕",
    ("tuning", "commas"): "𝒕𝐜",
    ("tuning", "targets"): "a",
    ("tuning", "held"): "𝒕𝐡",
    ("tuning", "detempering"): "𝒕𝐝",
    ("just", "primes"): "𝒋",
    ("just", "commas"): "𝒋𝐜",
    ("just", "targets"): "o",
    ("just", "held"): "𝒋𝐡",
    ("just", "detempering"): "𝒋𝐝",
    ("retune", "primes"): "𝒓",
    ("retune", "commas"): "𝒓𝐜",
    ("retune", "targets"): "e",
    ("retune", "held"): "𝒓𝐡",
    ("retune", "detempering"): "𝒓𝐝",
    ("damage", "targets"): "d",
    ("weight", "targets"): "w",
    ("tuning", "superspace_generators"): f"𝒈{SUBSCRIPT_L}",
    ("tuning", "superspace_primes"): f"𝒕{SUBSCRIPT_L}",
    ("just", "superspace_primes"): f"𝒋{SUBSCRIPT_L}",
    ("retune", "superspace_primes"): f"𝒓{SUBSCRIPT_L}",
}
_FACTOR_GROUP = {
    "G": "tuning",
    "J": "tuning",
    "X": "tuning",
    "T": "tuning",
    "H": "tuning",
    "P": "temperament",
    "B": "temperament",
    "M": "temperament",
    "C": "temperament",
    "F": "form",
}
CELL_FACTORS: dict[tuple[str, str], frozenset[str]] = {
    ("quantities", "generators"): frozenset({"B"}),
    ("quantities", "primes"): frozenset({"P"}),
    ("quantities", "commas"): frozenset({"C"}),
    ("vectors", "commas"): frozenset({"C"}),
    ("quantities", "targets"): frozenset({"T"}),
    ("vectors", "targets"): frozenset({"T"}),
    ("quantities", "held"): frozenset({"H"}),
    ("vectors", "held"): frozenset({"H"}),
    ("mapping", "primes"): frozenset({"M", "P"}),
    ("mapping", "commas"): frozenset({"M", "C"}),
    ("mapping", "targets"): frozenset({"M", "T"}),
    ("mapping", "interest"): frozenset({"M"}),
    ("mapping", "held"): frozenset({"M", "H"}),
    ("vectors", "primes"): frozenset({"M", "P"}),
    ("mapping", "generators"): frozenset({"M", "B"}),
    ("mapping", "detempering"): frozenset({"M"}),
    ("canonical", "targets"): frozenset({"T"}),
    ("canonical", "held"): frozenset({"H"}),
    ("projection", "primes"): frozenset({"P"}),
    ("projection", "generators"): frozenset({"B"}),
    ("tuning", "generators"): frozenset({"G", "B"}),
    ("tuning", "primes"): frozenset({"G", "M", "P"}),
    ("tuning", "commas"): frozenset({"G", "M", "C"}),
    ("tuning", "detempering"): frozenset({"G", "M"}),
    ("tuning", "targets"): frozenset({"G", "M", "T"}),
    ("tuning", "interest"): frozenset({"G", "M"}),
    ("tuning", "held"): frozenset({"G", "M", "H"}),
    ("just", "primes"): frozenset({"J", "P"}),
    ("just", "commas"): frozenset({"J", "C"}),
    ("just", "targets"): frozenset({"J", "T"}),
    ("just", "interest"): frozenset({"J"}),
    ("just", "held"): frozenset({"J", "H"}),
    ("just", "detempering"): frozenset({"J"}),
    ("retune", "primes"): frozenset({"G", "M", "J", "P"}),
    ("retune", "commas"): frozenset({"G", "M", "C", "J"}),
    ("retune", "detempering"): frozenset({"G", "M", "J"}),
    ("retune", "targets"): frozenset({"G", "M", "T", "J"}),
    ("retune", "interest"): frozenset({"G", "M", "J"}),
    ("retune", "held"): frozenset({"G", "M", "H", "J"}),
    ("damage", "targets"): frozenset({"G", "M", "T", "J"}),
    ("prescaling", "primes"): frozenset({"X", "P"}),
    ("prescaling", "superspace_primes"): frozenset({"X", "P"}),
    ("prescaling", "commas"): frozenset({"X", "C"}),
    ("prescaling", "targets"): frozenset({"X", "T"}),
    ("prescaling", "interest"): frozenset({"X"}),
    ("prescaling", "held"): frozenset({"X", "H"}),
    ("prescaling", "detempering"): frozenset({"X"}),
    ("complexity", "primes"): frozenset({"X", "P"}),
    ("complexity", "superspace_primes"): frozenset({"X", "P"}),
    ("complexity", "commas"): frozenset({"X", "C"}),
    ("complexity", "targets"): frozenset({"X", "T"}),
    ("complexity", "interest"): frozenset({"X"}),
    ("complexity", "held"): frozenset({"X", "H"}),
    ("complexity", "detempering"): frozenset({"X"}),
    ("weight", "targets"): frozenset({"X", "T"}),
}

SPINE_COLUMN_GROUP = {
    "generators": "temperament",
    "primes": "temperament",
    "commas": "temperament",
    "held": "tuning",
    "targets": "tuning",
}
SPINE_ROW_GROUP = {
    "mapping": "temperament",
    "tuning": "tuning",
    "just": "tuning",
    "retune": "tuning",
    "prescaling": "tuning",
    "complexity": "tuning",
    "weight": "tuning",
    "damage": frozenset({"tuning", "temperament"}),
}
SPINE_ROWS = frozenset({"counts", "units"})
SPINE_COLUMNS = frozenset({"quantities", "units"})

SUPERSPACE_REGION_COLUMNS = frozenset({"superspace_generators", "superspace_primes"})
SUPERSPACE_REGION_ROWS = frozenset({"superspace_vectors", "superspace_mapping", "superspace_projection"})

PRESETS = (
    ("temperament", "mapping", "primes", "temperament"),
    ("tuning", "tuning", "primes", "established tuning scheme"),
    ("target", "vectors", "targets", "target interval set scheme"),
    ("prescaler", "prescaling", "primes", "predefined prescalers"),
    ("projection", "projection", "primes", "established projection"),
)
PRESET_COPIES = (
    ("tuning", "tuning", "generators", "established tuning scheme"),
    ("temperament", "vectors", "commas", "temperament"),
    ("projection", "projection", "generators", "established embedding"),
)

FORM_CHOOSERS = (
    ("mapping", "mapping", "primes", "form"),
    ("comma_basis", "vectors", "commas", "form"),
)

MNEMONICS = {
    ("superspace_projection", "superspace_primes"): "projection",
    ("superspace_vectors", "primes"): "basis",
    ("vectors", "primes"): "mapping",
    ("mapping", "generators"): "mapped",
    ("mapping", "detempering"): "mapped",
    ("canonical", "primes"): "mapping",
    ("canonical", "generators"): "form",
    ("mapping", "canonical_generators"): "form",
    ("canonical", "detempering"): "mapped",
    ("canonical", "commas"): "mapped",
    ("canonical", "held"): "mapped",
    ("superspace_mapping", "superspace_primes"): "mapping",
    ("superspace_vectors", "superspace_primes"): "mapping",
    ("tuning", "superspace_generators"): "generator",
    ("tuning", "superspace_primes"): "tuning",
    ("just", "superspace_primes"): "just",
    ("retune", "superspace_primes"): "retuning",
    ("vectors", "commas"): "comma",
    ("vectors", "targets"): "target",
    ("vectors", "held"): "held",
    ("vectors", "detempering"): "detempering",
    ("mapping", "primes"): "mapping",
    ("tuning", "generators"): "generator",
    ("tuning", "primes"): "tuning",
    ("just", "primes"): "just",
    ("retune", "primes"): "retuning",
    ("retune", "targets"): "error",
    ("prescaling", "primes"): "x",
    ("prescaling", "superspace_primes"): "x",
    ("complexity", "targets"): "complexity",
    ("weight", "targets"): "weight",
    ("damage", "targets"): "damage",
}

EQUIVALENCES = {
    ("superspace_projection", "superspace_primes"): f" = G{SUBSCRIPT_L}𝑀{SUBSCRIPT_L}",
    ("tuning", "superspace_primes"): " = 𝒈L𝑀L",
    ("retune", "superspace_primes"): " = 𝒕L − 𝒋L",
    ("superspace_vectors", "superspace_primes"): " = 𝐼",
    ("superspace_vectors", "commas"): " = BLC",
    ("superspace_vectors", "held"): " = BLH",
    ("superspace_vectors", "targets"): " = BLT",
    ("superspace_vectors", "detempering"): " = BLD",
    ("superspace_mapping", "superspace_generators"): " = 𝐼",
    ("superspace_mapping", "superspace_primes"): " = null⁻¹(BL·null(𝑀))",
    ("superspace_mapping", "primes"): " = 𝑀LBL",
    ("superspace_mapping", "targets"): " = 𝑀ₛ→LT",
    ("mapping", "commas"): " = O",
    ("canonical", "detempering"): " = 𝐹",
    ("canonical", "commas"): " = O",
    ("canonical", "targets"): f" = 𝑀{SUBSCRIPT_C}T",
    ("vectors", "primes"): " = 𝐼",
    ("mapping", "generators"): " = 𝐼",
    ("mapping", "detempering"): " = 𝐼",
    ("canonical", "canonical_generators"): " = 𝐼",
    ("mapping", "targets"): " = 𝑀T",
    ("projection", "primes"): " = G𝑀 = V·diag(𝝀)V⁻¹",
    ("projection", "generators"): " = U(𝑀U)⁻¹",
    ("projection", "held"): " = H",
    ("projection", "superspace_primes"): f" = G{SUBSCRIPT_L}→ₛ𝑀{SUBSCRIPT_L}",
    ("tuning", "detempering"): " = 𝒈",
    ("tuning", "primes"): " = 𝒈𝑀",
    ("tuning", "targets"): " = 𝒕T = 𝒈𝑀T",
    ("just", "targets"): " = 𝒋T",
    ("retune", "primes"): " = 𝒕 − 𝒋",
    ("retune", "targets"): " = 𝒕T − 𝒋T = 𝐚 − 𝐨 = 𝒓T",
    ("damage", "targets"): " = |𝐞|𝒘",
    ("tuning", "held"): " = 𝒋H",
    ("just", "held"): " = 𝒕H",
    ("retune", "held"): " = 𝟎",
}

ALL_INTERVAL_SYMBOLS = {("vectors", "targets"): "Tₚ"}
ALL_INTERVAL_CAPTIONS = {("vectors", "targets"): "prime proxy target interval list"}
ALL_INTERVAL_EQUIVALENCES = {("vectors", "targets"): " = 𝐼"}
ALL_INTERVAL_MNEMONICS = {("vectors", "targets"): ("prime", "proxy")}

FORM_SUBSCRIPT_ROWS = frozenset({"mapping"})
FORM_SUBSCRIPT_GENS = frozenset({("tuning", "generators"), ("projection", "generators")})
FORM_EQUIVALENCES = {
    ("mapping", "targets"): f" = 𝑀{SUBSCRIPT_C}T",
    ("tuning", "detempering"): f" = 𝒈{SUBSCRIPT_C}",
    ("tuning", "primes"): f" = 𝒈{SUBSCRIPT_C}𝑀{SUBSCRIPT_C}",
    ("projection", "primes"): f" = G{SUBSCRIPT_C}𝑀{SUBSCRIPT_C} = V·diag(𝝀)V⁻¹",
    ("projection", "generators"): f" = U(𝑀{SUBSCRIPT_C}U)⁻¹",
}

UNITS = {
    ("vectors", "commas"): "p",
    ("projection", "commas"): "p",
    ("projection", "primes"): "p/p",
    ("projection", "superspace_generators"): f"b/g{SUBSCRIPT_L}",
    ("projection", "superspace_primes"): "b/p",
    ("projection", "generators"): "p/g",
    ("projection", "detempering"): "p",
    ("projection", "targets"): "p",
    ("projection", "held"): "p",
    ("projection", "interest"): "p",
    ("vectors", "targets"): "p",
    ("vectors", "held"): "p",
    ("vectors", "detempering"): "p",
    ("vectors", "interest"): "p",
    ("superspace_vectors", "superspace_primes"): "p/p",
    ("vectors", "primes"): "p/p",
    ("canonical", "primes"): f"g{SUBSCRIPT_C}/p",
    ("canonical", "generators"): f"g{SUBSCRIPT_C}/g",
    ("canonical", "canonical_generators"): f"g{SUBSCRIPT_C}/g{SUBSCRIPT_C}",
    ("mapping", "canonical_generators"): f"g/g{SUBSCRIPT_C}",
    ("projection", "canonical_generators"): f"p/g{SUBSCRIPT_C}",
    ("tuning", "canonical_generators"): f"¢/g{SUBSCRIPT_C}",
    ("mapping", "generators"): "g/g",
    ("mapping", "detempering"): "g",
    ("superspace_vectors", "primes"): "p/b",
    ("superspace_vectors", "commas"): "p",
    ("superspace_vectors", "held"): "p",
    ("superspace_vectors", "targets"): "p",
    ("superspace_vectors", "interest"): "p",
    ("superspace_vectors", "detempering"): "p",
    ("superspace_mapping", "superspace_generators"): f"g{SUBSCRIPT_L}/g{SUBSCRIPT_L}",
    ("superspace_mapping", "superspace_primes"): f"g{SUBSCRIPT_L}/p",
    ("superspace_mapping", "primes"): f"g{SUBSCRIPT_L}/b",
    ("superspace_mapping", "commas"): f"g{SUBSCRIPT_L}",
    ("superspace_mapping", "held"): f"g{SUBSCRIPT_L}",
    ("superspace_mapping", "targets"): f"g{SUBSCRIPT_L}",
    ("superspace_mapping", "interest"): f"g{SUBSCRIPT_L}",
    ("superspace_mapping", "detempering"): f"g{SUBSCRIPT_L}",
    ("superspace_projection", "superspace_primes"): "p/p",
    ("superspace_projection", "superspace_generators"): f"p/g{SUBSCRIPT_L}",
    ("superspace_projection", "primes"): "p/b",
    ("superspace_projection", "detempering"): "p",
    ("superspace_projection", "commas"): "p",
    ("superspace_projection", "targets"): "p",
    ("superspace_projection", "held"): "p",
    ("superspace_projection", "interest"): "p",
    ("tuning", "superspace_generators"): f"¢/g{SUBSCRIPT_L}",
    ("tuning", "superspace_primes"): "¢/p",
    ("just", "superspace_primes"): "¢/p",
    ("retune", "superspace_primes"): "¢/p",
    ("mapping", "primes"): "g/p",
    ("mapping", "commas"): "g",
    ("mapping", "targets"): "g",
    ("mapping", "interest"): "g",
    ("canonical", "detempering"): f"g{SUBSCRIPT_C}",
    ("canonical", "commas"): f"g{SUBSCRIPT_C}",
    ("canonical", "held"): f"g{SUBSCRIPT_C}",
    ("canonical", "targets"): f"g{SUBSCRIPT_C}",
    ("canonical", "interest"): f"g{SUBSCRIPT_C}",
    ("tuning", "generators"): "¢/g",
    ("tuning", "primes"): "¢/p",
    ("tuning", "commas"): "¢",
    ("tuning", "detempering"): "¢",
    ("tuning", "targets"): "¢",
    ("tuning", "interest"): "¢",
    ("just", "primes"): "¢/p",
    ("just", "commas"): "¢",
    ("just", "detempering"): "¢",
    ("just", "targets"): "¢",
    ("just", "interest"): "¢",
    ("retune", "primes"): "¢/p",
    ("retune", "commas"): "¢",
    ("retune", "detempering"): "¢",
    ("retune", "targets"): "¢",
    ("retune", "interest"): "¢",
    ("damage", "targets"): "¢",
    ("prescaling", "primes"): "oct/p",
    ("prescaling", "superspace_primes"): "oct/p",
    ("prescaling", "commas"): "oct",
    ("prescaling", "detempering"): "oct",
    ("prescaling", "targets"): "oct",
    ("prescaling", "interest"): "oct",
    ("complexity", "primes"): "(C)/p",
    ("complexity", "superspace_primes"): "(C)/p",
    ("complexity", "commas"): "(C)",
    ("complexity", "detempering"): "(C)",
    ("complexity", "targets"): "(C)",
    ("complexity", "interest"): "(C)",
    ("weight", "targets"): "(C)",
    ("mapping", "held"): "g",
    ("tuning", "held"): "¢",
    ("just", "held"): "¢",
    ("retune", "held"): "¢",
    ("prescaling", "held"): "oct",
    ("complexity", "held"): "(C)",
}


@dataclass(frozen=True)
class Band:
    name: str
    rows: frozenset
    height: float | None = None


def _carrier_rows(table):
    return frozenset(row_key for row_key, _ckey in table)


BANDS = {
    band.name: band
    for band in (
        Band("symbol", _carrier_rows(SYMBOLS), SYMBOL_HEIGHT),
        Band("caption", _carrier_rows(CAPTIONS)),
        Band("units", _carrier_rows(UNITS), UNIT_HEIGHT),
        Band("col_label", _carrier_rows(COLUMN_LABEL_LETTERS) | {"prescaling", "complexity"}),
        Band("frame", frozenset({"mapping", "canonical", "vectors", "prescaling",
                                 "superspace_vectors", "superspace_mapping", "superspace_projection", "projection"})),
        Band("chart", frozenset({"retune", "weight", "damage"})),
        Band("preset", frozenset(row_key for _name, row_key, _ckey, _label in PRESETS + PRESET_COPIES)),
        Band("form_chooser", frozenset(row_key for _name, row_key, _ckey, _label in FORM_CHOOSERS)),
    )
}

FRAMED_ROWS = BANDS["frame"].rows

WEIGHT_EQUIVALENCE_BY_SLOPE = {
    "complexityWeight": " = 𝒄",
    "unityWeight": " = 𝟏",
    "simplicityWeight": " = 𝒄⁻¹",
}

PRESCALER_LETTER = {"log-prime": "𝐿", "prime": "diag(𝒑)", "identity": "𝐼"}

TILES = (
    ("block:quantities_generators", "quantities", "generators"),
    ("block:primes", "quantities", "primes"),
    ("block:commas", "quantities", "commas"),
    ("block:targets", "quantities", "targets"),
    ("block:vector:quantities", "vectors", "quantities"),
    ("block:vector:commas", "vectors", "commas"),
    ("block:vector:targets", "vectors", "targets"),
    ("block:canonical_generators", "quantities", "canonical_generators"),
    ("block:canonical_spine", "canonical", "quantities"),
    ("block:inverse_form", "canonical", "generators"),
    ("block:fcancel", "canonical", "canonical_generators"),
    ("block:form", "mapping", "canonical_generators"),
    ("block:embed_c", "projection", "canonical_generators"),
    ("block:tuning:canonical_generators", "tuning", "canonical_generators"),
    ("block:canonical", "canonical", "primes"),
    ("block:generators", "mapping", "quantities"),
    ("block:mapping", "mapping", "primes"),
    ("block:vector:primes", "vectors", "primes"),
    ("block:selfmap", "mapping", "generators"),
    ("block:projection", "projection", "primes"),
    ("block:projection_embedding", "projection", "generators"),
    ("block:projection_vectors", "projection", "commas"),
    ("block:scaling_factors", "scaling_factors", "commas"),
    ("block:mapped_comma", "mapping", "commas"),
    ("block:mapped", "mapping", "targets"),
    ("block:tuning:generators", "tuning", "generators"),
    ("block:tuning:primes", "tuning", "primes"),
    ("block:tuning:commas", "tuning", "commas"),
    ("block:tuning:targets", "tuning", "targets"),
    ("block:just:primes", "just", "primes"),
    ("block:just:commas", "just", "commas"),
    ("block:just:targets", "just", "targets"),
    ("block:retune:primes", "retune", "primes"),
    ("block:retune:commas", "retune", "commas"),
    ("block:retune:targets", "retune", "targets"),
    ("block:prescaling:primes", "prescaling", "primes"),
    ("block:prescaling:commas", "prescaling", "commas"),
    ("block:prescaling:targets", "prescaling", "targets"),
    ("block:complexity:primes", "complexity", "primes"),
    ("block:complexity:commas", "complexity", "commas"),
    ("block:complexity:targets", "complexity", "targets"),
    ("block:weight:targets", "weight", "targets"),
    ("block:damage:targets", "damage", "targets"),
)

SUPERSPACE_TILES = (
    ("block:superspace_quantities:superspace_generators", "quantities", "superspace_generators"),
    ("block:superspace_quantities:superspace_primes", "quantities", "superspace_primes"),
    ("block:superspace_vectors:quantities", "superspace_vectors", "quantities"),
    ("block:superspace_vectors:superspace_primes", "superspace_vectors", "superspace_primes"),
    ("block:superspace_vectors:primes", "superspace_vectors", "primes"),
    ("block:superspace_vectors:commas", "superspace_vectors", "commas"),
    ("block:superspace_vectors:held", "superspace_vectors", "held"),
    ("block:superspace_vectors:targets", "superspace_vectors", "targets"),
    ("block:superspace_vectors:interest", "superspace_vectors", "interest"),
    ("block:superspace_vectors:detempering", "superspace_vectors", "detempering"),
    ("block:superspace_mapping:quantities", "superspace_mapping", "quantities"),
    ("block:superspace_mapping:superspace_generators", "superspace_mapping", "superspace_generators"),
    ("block:superspace_mapping:superspace_primes", "superspace_mapping", "superspace_primes"),
    ("block:superspace_mapping:primes", "superspace_mapping", "primes"),
    ("block:superspace_mapping:commas", "superspace_mapping", "commas"),
    ("block:superspace_mapping:held", "superspace_mapping", "held"),
    ("block:superspace_mapping:targets", "superspace_mapping", "targets"),
    ("block:superspace_mapping:interest", "superspace_mapping", "interest"),
    ("block:superspace_mapping:detempering", "superspace_mapping", "detempering"),
    ("block:superspace_projection:superspace_primes", "superspace_projection", "superspace_primes"),
    ("block:superspace_projection:quantities", "superspace_projection", "quantities"),
    ("block:tuning:superspace_generators", "tuning", "superspace_generators"),
    ("block:tuning:superspace_primes", "tuning", "superspace_primes"),
    ("block:just:superspace_primes", "just", "superspace_primes"),
    ("block:retune:superspace_primes", "retune", "superspace_primes"),
    ("block:prescaling:superspace_primes", "prescaling", "superspace_primes"),
    ("block:complexity:superspace_primes", "complexity", "superspace_primes"),
)


UNITS_TILES = (
    ("block:units_column:vectors", "vectors", "units"),
    ("block:units_column:canonical", "canonical", "units"),
    ("block:units_column:mapping", "mapping", "units"),
    ("block:units_column:tuning", "tuning", "units"),
    ("block:units_column:just", "just", "units"),
    ("block:units_column:retune", "retune", "units"),
    ("block:units_column:prescaling", "prescaling", "units"),
    ("block:units_column:complexity", "complexity", "units"),
    ("block:units_column:weight", "weight", "units"),
    ("block:units_column:damage", "damage", "units"),
    ("block:units_row:canonical_generators", "units", "canonical_generators"),
    ("block:units_row:generators", "units", "generators"),
    ("block:units_row:primes", "units", "primes"),
    ("block:units_row:commas", "units", "commas"),
    ("block:units_row:targets", "units", "targets"),
    ("block:units_column:superspace_vectors", "superspace_vectors", "units"),
    ("block:units_column:superspace_mapping", "superspace_mapping", "units"),
    ("block:units_column:superspace_projection", "superspace_projection", "units"),
    ("block:units_row:superspace_generators", "units", "superspace_generators"),
    ("block:units_row:superspace_primes", "units", "superspace_primes"),
)

EDITABLE_PLAIN_TEXT = frozenset(
    {
        ("mapping", "primes"),
        ("vectors", "commas"),
        ("tuning", "generators"),
        ("vectors", "targets"),
        ("prescaling", "primes"),
        ("mapping", "canonical_generators"),
        ("projection", "primes"),
        ("projection", "generators"),
    }
)
EDITABLE_PLAIN_TEXT_ROWS = frozenset(r for r, _ in EDITABLE_PLAIN_TEXT)
PLAIN_TEXT_ROWS = frozenset(
    {
        "quantities",
        "vectors",
        "mapping",
        "canonical",
        "tuning",
        "just",
        "retune",
        "damage",
        "prescaling",
        "complexity",
        "weight",
        "projection",
        "scaling_factors",
        "superspace_vectors",
        "superspace_mapping",
        "superspace_projection",
    }
)

GRIDDED_VALUE_KINDS = frozenset(
    {
        "prime",
        "ratio_cell",
        "comma_ratio",
        "generator_ratio",
        "mapping",
        "mapped",
        "comma_cell",
        "vector",
        "tuning_value",
        "math_expression",
        "interest_cell",
        "form_cell",
        "held_cell",
        "generator_tuning_cell",
        "target_cell",
        "prescaler_cell",
        "element_cell",
        "element_ratio",
        "unchanged_cell",
        "power_input",
        "power_display",
    }
)
BLANKED_NUMBER_KINDS = frozenset(
    {
        "generator_ratio",
        "mapping",
        "mapped",
        "comma_cell",
        "vector",
        "tuning_value",
        "interest_cell",
        "form_cell",
        "held_cell",
        "generator_tuning_cell",
        "target_cell",
        "prescaler_cell",
        "prime",
        "element_cell",
        "element_ratio",
        "ratio_cell",
        "comma_ratio",
        "unchanged_cell",
    }
)

RINGABLE_KINDS = BLANKED_NUMBER_KINDS | frozenset(
    {
        "math_expression",
        "power_display",
    }
)
