NORM_SUB_OPEN = chr(0xE001)
NORM_SUB_CLOSE = chr(0xE002)
SUB_OPEN = chr(0xE003)
SUB_CLOSE = chr(0xE004)
SUBSCRIPT_L = SUB_OPEN + "L" + SUB_CLOSE
SUBSCRIPT_J = SUB_OPEN + "j" + SUB_CLOSE
SUBSCRIPT_C = SUB_OPEN + "C" + SUB_CLOSE

COUNTS = (
    ("gens", "r", "rank"),
    ("primes", "d", "dimensionality"),
    ("commas", "n", "nullity"),
    ("targets", "k", "target interval count"),
)
COUNTS_TILES = tuple((f"block:counts:{ckey}", "counts", ckey) for ckey, *_ in COUNTS)

OPTIMIZATION_COUNTS = (
    ("held", "h", "held interval count"),
)
OPTIMIZATION_COUNTS_TILES = tuple(
    (f"block:counts:{ckey}", "counts", ckey) for ckey, *_ in OPTIMIZATION_COUNTS
)
DETEMPERING_COUNTS = (
    ("detempering", "r", "rank"),
)
DETEMPERING_COUNTS_TILES = tuple(
    (f"block:counts:{ckey}", "counts", ckey) for ckey, *_ in DETEMPERING_COUNTS
)

SUPERSPACE_COUNTS = (
    ("ssgens", "rL", "superspace rank"),
    ("ssprimes", "dL", "superspace dimensionality"),
)
SUPERSPACE_COUNTS_TILES = tuple(
    (f"block:counts:{ckey}", "counts", ckey) for ckey, *_ in SUPERSPACE_COUNTS
)

CAPTIONS = {
    ("ss_vectors", "ssprimes"): "superspace JI mapping",
    ("ss_vectors", "primes"): "basis change matrix",
    ("ss_vectors", "commas"): "comma basis in superspace",
    ("ss_vectors", "held"): "held interval basis in superspace",
    ("ss_vectors", "targets"): "target interval list in superspace",
    ("ss_vectors", "interest"): "intervals in superspace",
    ("ss_vectors", "detempering"): "generator detempering in superspace",
    ("ss_mapping", "ssgens"): "superspace mapped generators",
    ("ss_mapping", "ssprimes"): "superspace mapping",
    ("ss_mapping", "primes"): "mapping from domain intervals to superspace generators",
    ("ss_mapping", "commas"): "comma basis in superspace generators",
    ("ss_mapping", "held"): "held interval basis in superspace generators",
    ("ss_mapping", "targets"): "target interval list in superspace generators",
    ("ss_mapping", "interest"): "intervals in superspace generators",
    ("ss_mapping", "detempering"): "generator detempering in superspace generators",
    ("ss_projection", "ssprimes"): "superspace projection",
    ("ss_projection", "ssgens"): "superspace generator embedding",
    ("ss_projection", "primes"): "superspace projected subspace basis elements",
    ("ss_projection", "detempering"): "projected generator detempering in superspace",
    ("ss_projection", "commas"): "projected comma basis in superspace",
    ("ss_projection", "targets"): "projected target interval list in superspace",
    ("ss_projection", "held"): "projected held interval basis in superspace",
    ("ss_projection", "interest"): "projected intervals in superspace",
    ("tuning", "ssgens"): "superspace generator tuning map",
    ("tuning", "ssprimes"): "superspace tuning map",
    ("just", "ssprimes"): "superspace just tuning map",
    ("retune", "ssprimes"): "superspace retuning map",
    ("vectors", "commas"): "comma basis",
    ("vectors", "targets"): "target interval list",
    ("canon", "gens"): "inverse generator form matrix",
    ("canon", "canongens"): "form matrices canceling out",
    ("canon", "primes"): "canonical mapping",
    ("mapping", "canongens"): "generator form matrix",
    ("projection", "canongens"): "canonical generator embedding",
    ("tuning", "canongens"): "canonical generator tuning map",
    ("canon", "detempering"): "canonically mapped generator detempering",
    ("canon", "commas"): "canonically mapped comma basis (made to vanish!)",
    ("canon", "held"): "canonically mapped held interval basis",
    ("canon", "targets"): "canonically mapped target interval list",
    ("canon", "interest"): "canonically mapped intervals",
    ("vectors", "held"): "held interval basis",
    ("vectors", "detempering"): "generator detempering",
    ("vectors", "primes"): "JI mapping",
    ("mapping", "primes"): "(temperament) mapping",
    ("mapping", "gens"): "mapped generators",
    ("mapping", "detempering"): "mapped generator detempering",
    ("mapping", "commas"): "mapped comma basis (made to vanish!)",
    ("mapping", "targets"): "mapped target interval list",
    ("projection", "primes"): "projection",
    ("projection", "gens"): "generator embedding",
    ("projection", "commas"): "projected unrotated vector list",
    ("projection", "detempering"): "projected generator detempering",
    ("projection", "targets"): "projected target interval list",
    ("projection", "held"): "projected held interval basis",
    ("projection", "interest"): "projected intervals",
    ("projection", "ssgens"): "embedding from superspace generators to subspace elements",
    ("projection", "ssprimes"): "projection from superspace to subspace",
    ("scaling_factors", "commas"): "scaling factor (eigenvalue) list",
    ("tuning", "gens"): "generator tuning map",
    ("tuning", "primes"): "tuning map",
    ("tuning", "commas"): "tempered comma basis interval size list (made to vanish!)",
    ("tuning", "detempering"): "(retempered) generator tuning map",
    ("tuning", "targets"): "tempered target interval size list",
    ("just", "primes"): "just tuning map",
    ("just", "commas"): "(just) comma basis interval size list",
    ("just", "detempering"): "(just) generator detempering interval size list",
    ("just", "targets"): "(just) target interval size list",
    ("retune", "primes"): "retuning map",
    ("retune", "commas"): "comma basis interval retuning list (made to vanish!)",
    ("retune", "detempering"): "generator detempering interval retuning list",
    ("retune", "targets"): "target interval error list",
    ("prescaling", "primes"): "complexity prescaler",
    ("prescaling", "ssprimes"): "(superspace) complexity prescaler",
    ("prescaling", "commas"): "complexity prescaled comma basis",
    ("prescaling", "detempering"): "complexity prescaled generator detempering",
    ("prescaling", "targets"): "complexity prescaled target interval list",
    ("complexity", "primes"): "domain prime complexity map",
    ("complexity", "ssprimes"): "domain prime complexity map",
    ("complexity", "commas"): "comma basis interval complexity list",
    ("complexity", "detempering"): "generator detempering complexity list",
    ("complexity", "targets"): "target interval complexity list",
    ("weight", "targets"): "target interval weight list",
    ("damage", "targets"): "target interval damage list",
    **{("counts", ckey): name for ckey, _sym, name in
       COUNTS + OPTIMIZATION_COUNTS + DETEMPERING_COUNTS + SUPERSPACE_COUNTS},
    ("vectors", "interest"): "intervals of interest",
    ("mapping", "interest"): "mapped intervals",
    ("tuning", "interest"): "tempered interval sizes",
    ("just", "interest"): "(just) interval sizes",
    ("retune", "interest"): "interval retunings",
    ("prescaling", "interest"): "complexity prescaled intervals",
    ("complexity", "interest"): "interval complexities",
    ("mapping", "held"): "mapped held interval basis",
    ("tuning", "held"): "tempered held interval basis interval size list",
    ("just", "held"): "(just) held interval basis interval size list",
    ("retune", "held"): "held interval basis interval retuning list",
    ("prescaling", "held"): "complexity prescaled held interval basis",
    ("complexity", "held"): "held interval basis interval complexity list",
}
CAPTIONED_ROWS = frozenset(row for row, _ in CAPTIONS)
SYMBOLS = {
    ("ss_vectors", "primes"): "BL",
    ("ss_mapping", "ssprimes"): "𝑀L",
    ("tuning", "ssgens"): "𝒈L",
    ("tuning", "ssprimes"): "𝒕L",
    ("just", "ssprimes"): "𝒋L",
    ("retune", "ssprimes"): "𝒓L",
    ("ss_vectors", "ssprimes"): f"𝑀{SUBSCRIPT_J}{SUBSCRIPT_L}",
    ("ss_vectors", "commas"): f"C{SUBSCRIPT_L}",
    ("ss_vectors", "held"): f"H{SUBSCRIPT_L}",
    ("ss_vectors", "targets"): f"T{SUBSCRIPT_L}",
    ("ss_vectors", "detempering"): f"D{SUBSCRIPT_L}",
    ("ss_mapping", "ssgens"): f"𝑀{SUBSCRIPT_L}G{SUBSCRIPT_L}",
    ("ss_mapping", "primes"): f"𝑀ₛ→{SUBSCRIPT_L}",
    ("ss_mapping", "commas"): f"𝑀ₛ→{SUBSCRIPT_L}C",
    ("ss_mapping", "held"): f"𝑀ₛ→{SUBSCRIPT_L}H",
    ("ss_mapping", "targets"): f"Y{SUBSCRIPT_L}",
    ("ss_mapping", "detempering"): f"𝑀ₛ→{SUBSCRIPT_L}D",
    ("scaling_factors", "commas"): "𝝀",
    ("projection", "commas"): "𝑃V",
    ("projection", "primes"): "𝑃",
    ("projection", "gens"): "G",
    ("projection", "detempering"): "𝑃D",
    ("projection", "targets"): "𝑃T",
    ("projection", "held"): "𝑃H",
    ("projection", "ssgens"): f"G{SUBSCRIPT_L}→ₛ",
    ("projection", "ssprimes"): f"𝑃{SUBSCRIPT_L}→ₛ",
    ("ss_projection", "ssprimes"): f"𝑃{SUBSCRIPT_L}",
    ("ss_projection", "ssgens"): f"G{SUBSCRIPT_L}",
    ("ss_projection", "primes"): f"𝑃{SUBSCRIPT_L}B{SUBSCRIPT_L}",
    ("ss_projection", "detempering"): f"𝑃{SUBSCRIPT_L}D{SUBSCRIPT_L}",
    ("ss_projection", "commas"): f"𝑃{SUBSCRIPT_L}C{SUBSCRIPT_L}",
    ("ss_projection", "targets"): f"𝑃{SUBSCRIPT_L}T{SUBSCRIPT_L}",
    ("ss_projection", "held"): f"𝑃{SUBSCRIPT_L}H{SUBSCRIPT_L}",
    ("vectors", "commas"): "C",
    ("vectors", "targets"): "T",
    ("vectors", "detempering"): "D",
    ("vectors", "primes"): "𝑀" + SUBSCRIPT_J,
    ("canon", "primes"): f"𝑀{SUBSCRIPT_C}",
    ("canon", "gens"): "𝐹⁻¹",
    ("canon", "detempering"): f"𝑀{SUBSCRIPT_C}D",
    ("canon", "commas"): f"𝑀{SUBSCRIPT_C}C",
    ("canon", "held"): f"𝑀{SUBSCRIPT_C}H",
    ("canon", "targets"): f"Y{SUBSCRIPT_C}",
    ("mapping", "primes"): "𝑀",
    ("canon", "canongens"): "𝐹⁻¹𝐹",
    ("mapping", "canongens"): "𝐹",
    ("projection", "canongens"): f"G{SUBSCRIPT_C}",
    ("tuning", "canongens"): f"𝒈{SUBSCRIPT_C}",
    ("mapping", "gens"): "𝑀G",
    ("mapping", "detempering"): "𝑀D",
    ("mapping", "commas"): "𝑀C",
    ("mapping", "targets"): "Y",
    ("tuning", "gens"): "𝒈",
    ("tuning", "primes"): "𝒕",
    ("tuning", "commas"): "𝒕C",
    ("tuning", "detempering"): "𝒕D",
    ("tuning", "targets"): "𝐚",
    ("just", "primes"): "𝒋",
    ("just", "commas"): "𝒋C",
    ("just", "detempering"): "𝒋D",
    ("just", "targets"): "𝐨",
    ("retune", "primes"): "𝒓",
    ("retune", "commas"): "𝒓C",
    ("retune", "detempering"): "𝒓D",
    ("retune", "targets"): "𝐞",
    ("prescaling", "primes"): "𝑋",
    ("prescaling", "ssprimes"): "𝑋",
    ("prescaling", "commas"): "LC",
    ("prescaling", "detempering"): "LD",
    ("prescaling", "targets"): "LT",
    ("prescaling", "held"): "LH",
    ("vectors", "held"): "H",
    ("mapping", "held"): "𝑀H",
    ("tuning", "held"): "𝒕H",
    ("just", "held"): "𝒋H",
    ("retune", "held"): "𝒓H",
    ("complexity", "targets"): "𝒄",
    ("weight", "targets"): "𝒘",
    ("damage", "targets"): "𝐝",
}
SYMBOLED_ROWS = frozenset(row for row, _ in SYMBOLS)
ROW_LABEL_LETTERS = {
    ("mapping", "primes"): "𝒎",
    ("canon", "primes"): f"𝒎{SUBSCRIPT_C}",
    ("mapping", "canongens"): "𝒇",
    ("vectors", "primes"): "𝒎" + SUBSCRIPT_J,
    ("projection", "primes"): "𝒑",
    ("projection", "ssprimes"): f"𝒑{SUBSCRIPT_L}→ₛ",
    ("prescaling", "primes"): "𝒙",
    ("prescaling", "ssprimes"): "𝒙",
    ("ss_mapping", "ssprimes"): "𝒎L",
    ("ss_mapping", "primes"): "𝒎ₛ→L",
    ("ss_vectors", "ssprimes"): "𝒎" + SUBSCRIPT_J + SUBSCRIPT_L,
    ("ss_projection", "ssprimes"): f"𝒑{SUBSCRIPT_L}",
}
COL_LABEL_LETTERS = {
    ("mapping", "detempering"): "𝑀𝐝",
    ("scaling_factors", "commas"): "𝜆",
    ("projection", "commas"): "𝑃𝐯",
    ("projection", "gens"): "𝐠",
    ("projection", "canongens"): f"𝐠{SUBSCRIPT_C}",
    ("tuning", "canongens"): f"𝒈{SUBSCRIPT_C}",
    ("projection", "ssgens"): f"𝐠{SUBSCRIPT_L}→ₛ",
    ("projection", "detempering"): "𝑃𝐝",
    ("projection", "targets"): "𝑃𝐭",
    ("projection", "held"): "𝑃𝐡",
    ("projection", "interest"): "𝑃𝐢",
    ("ss_projection", "ssgens"): f"𝐠{SUBSCRIPT_L}",
    ("ss_projection", "primes"): f"𝑃{SUBSCRIPT_L}𝐛",
    ("ss_projection", "detempering"): f"𝑃{SUBSCRIPT_L}𝐝",
    ("ss_projection", "commas"): f"𝑃{SUBSCRIPT_L}𝐜",
    ("ss_projection", "targets"): f"𝑃{SUBSCRIPT_L}𝐭",
    ("ss_projection", "held"): f"𝑃{SUBSCRIPT_L}𝐡",
    ("ss_projection", "interest"): f"𝑃{SUBSCRIPT_L}𝐢",
    ("vectors", "commas"): "𝐜",
    ("vectors", "targets"): "𝐭",
    ("vectors", "held"): "𝐡",
    ("vectors", "detempering"): "𝐝",
    ("ss_vectors", "primes"): "𝐛",
    ("ss_vectors", "commas"): f"𝐜{SUBSCRIPT_L}",
    ("ss_vectors", "held"): f"𝐡{SUBSCRIPT_L}",
    ("ss_vectors", "targets"): f"𝐭{SUBSCRIPT_L}",
    ("ss_vectors", "detempering"): f"𝐝{SUBSCRIPT_L}",
    ("ss_mapping", "commas"): f"𝑀{SUBSCRIPT_L}𝐜",
    ("ss_mapping", "targets"): f"𝐲{SUBSCRIPT_L}",
    ("ss_mapping", "held"): f"𝑀{SUBSCRIPT_L}𝐡",
    ("ss_mapping", "detempering"): f"𝑀{SUBSCRIPT_L}𝐝",
    ("mapping", "commas"): "𝑀𝐜",
    ("mapping", "targets"): "𝐲",
    ("mapping", "held"): "𝑀𝐡",
    ("canon", "detempering"): f"𝑀{SUBSCRIPT_C}𝐝",
    ("canon", "commas"): f"𝑀{SUBSCRIPT_C}𝐜",
    ("canon", "targets"): f"𝐲{SUBSCRIPT_C}",
    ("canon", "held"): f"𝑀{SUBSCRIPT_C}𝐡",
    ("canon", "interest"): f"𝑀{SUBSCRIPT_C}𝐢",
    ("tuning", "gens"): "𝒈",
    ("tuning", "primes"): "𝒕",
    ("tuning", "commas"): "𝒕𝐜",
    ("tuning", "targets"): "a",
    ("tuning", "held"): "𝒕𝐡",
    ("tuning", "detempering"): "𝒕𝐝",
    ("just", "primes"): "𝒋",
    ("just", "commas"): "𝒋𝐜",
    ("just", "targets"): "o",
    ("just", "held"): "𝒋𝐡",
    ("just", "detempering"): "𝒋𝐝",
    ("retune", "primes"): "𝒓",
    ("retune", "commas"): "𝒓𝐜",
    ("retune", "targets"): "e",
    ("retune", "held"): "𝒓𝐡",
    ("retune", "detempering"): "𝒓𝐝",
    ("damage", "targets"): "d",
    ("weight", "targets"): "w",
    ("tuning", "ssgens"): f"𝒈{SUBSCRIPT_L}",
    ("tuning", "ssprimes"): f"𝒕{SUBSCRIPT_L}",
    ("just", "ssprimes"): f"𝒋{SUBSCRIPT_L}",
    ("retune", "ssprimes"): f"𝒓{SUBSCRIPT_L}",
}
FRAMED_ROWS = frozenset({"mapping", "canon", "vectors", "prescaling",
                         "ss_vectors", "ss_mapping", "ss_projection",
                         "projection"})
CHARTED_ROWS = frozenset({"retune", "weight", "damage"})
COL_LABELED_ROWS = frozenset(rkey for rkey, _ in COL_LABEL_LETTERS) | {"prescaling", "complexity"}

_FACTOR_GROUP = {"G": "tuning", "J": "tuning", "X": "tuning", "T": "tuning", "H": "tuning",
                 "P": "temperament", "B": "temperament", "M": "temperament", "C": "temperament",
                 "F": "form"}
CELL_FACTORS: dict[tuple[str, str], frozenset[str]] = {
    ("quantities", "gens"): frozenset({"B"}),
    ("quantities", "primes"): frozenset({"P"}),
    ("quantities", "commas"): frozenset({"C"}),
    ("vectors", "commas"): frozenset({"C"}),
    ("quantities", "targets"): frozenset({"T"}),
    ("vectors", "targets"): frozenset({"T"}),
    ("quantities", "held"): frozenset({"H"}),
    ("vectors", "held"): frozenset({"H"}),
    ("mapping", "primes"): frozenset({"M", "P"}),
    ("mapping", "commas"): frozenset({"M", "C"}),
    ("mapping", "targets"): frozenset({"M", "T"}),
    ("mapping", "interest"): frozenset({"M"}),
    ("mapping", "held"): frozenset({"M", "H"}),
    ("vectors", "primes"): frozenset({"M", "P"}),
    ("mapping", "gens"): frozenset({"M", "B"}),
    ("mapping", "detempering"): frozenset({"M"}),
    ("canon", "targets"): frozenset({"T"}),
    ("canon", "held"): frozenset({"H"}),
    ("projection", "primes"): frozenset({"P"}),
    ("projection", "gens"): frozenset({"B"}),
    ("tuning", "gens"): frozenset({"G", "B"}),
    ("tuning", "primes"): frozenset({"G", "M", "P"}),
    ("tuning", "commas"): frozenset({"G", "M", "C"}),
    ("tuning", "detempering"): frozenset({"G", "M"}),
    ("tuning", "targets"): frozenset({"G", "M", "T"}),
    ("tuning", "interest"): frozenset({"G", "M"}),
    ("tuning", "held"): frozenset({"G", "M", "H"}),
    ("just", "primes"): frozenset({"J", "P"}),
    ("just", "commas"): frozenset({"J", "C"}),
    ("just", "targets"): frozenset({"J", "T"}),
    ("just", "interest"): frozenset({"J"}),
    ("just", "held"): frozenset({"J", "H"}),
    ("just", "detempering"): frozenset({"J"}),
    ("retune", "primes"): frozenset({"G", "M", "J", "P"}),
    ("retune", "commas"): frozenset({"G", "M", "C", "J"}),
    ("retune", "detempering"): frozenset({"G", "M", "J"}),
    ("retune", "targets"): frozenset({"G", "M", "T", "J"}),
    ("retune", "interest"): frozenset({"G", "M", "J"}),
    ("retune", "held"): frozenset({"G", "M", "H", "J"}),
    ("damage", "targets"): frozenset({"G", "M", "T", "J"}),
    ("prescaling", "primes"): frozenset({"X", "P"}),
    ("prescaling", "ssprimes"): frozenset({"X", "P"}),
    ("prescaling", "commas"): frozenset({"X", "C"}),
    ("prescaling", "targets"): frozenset({"X", "T"}),
    ("prescaling", "interest"): frozenset({"X"}),
    ("prescaling", "held"): frozenset({"X", "H"}),
    ("prescaling", "detempering"): frozenset({"X"}),
    ("complexity", "primes"): frozenset({"X", "P"}),
    ("complexity", "ssprimes"): frozenset({"X", "P"}),
    ("complexity", "commas"): frozenset({"X", "C"}),
    ("complexity", "targets"): frozenset({"X", "T"}),
    ("complexity", "interest"): frozenset({"X"}),
    ("complexity", "held"): frozenset({"X", "H"}),
    ("complexity", "detempering"): frozenset({"X"}),
    ("weight", "targets"): frozenset({"X", "T"}),
}

SPINE_COLUMN_GROUP = {
    "gens": "temperament", "primes": "temperament", "commas": "temperament",
    "held": "tuning", "targets": "tuning",
}
SPINE_ROW_GROUP = {
    "mapping": "temperament",
    "tuning": "tuning", "just": "tuning", "retune": "tuning",
    "prescaling": "tuning", "complexity": "tuning",
    "weight": "tuning",
    "damage": frozenset({"tuning", "temperament"}),
}
SPINE_ROWS = frozenset({"counts", "units"})
SPINE_COLUMNS = frozenset({"quantities", "units"})

SUPERSPACE_REGION_COLUMNS = frozenset({"ssgens", "ssprimes"})
SUPERSPACE_REGION_ROWS = frozenset({"ss_vectors", "ss_mapping", "ss_projection"})

PRESETS = (
    ("temperament", "mapping", "primes", "temperament"),
    ("tuning", "tuning", "primes", "established tuning scheme"),
    ("target", "vectors", "targets", "target interval set scheme"),
    ("prescaler", "prescaling", "primes", "predefined prescalers"),
    ("projection", "projection", "primes", "established projection"),
)
PRESET_COPIES = (
    ("tuning", "tuning", "gens", "established tuning scheme"),
    ("temperament", "vectors", "commas", "temperament"),
    ("projection", "projection", "gens", "established embedding"),
)
PRESET_ROWS = frozenset(row for _, row, _, _ in PRESETS + PRESET_COPIES)

FORM_CHOOSERS = (
    ("mapping", "mapping", "primes", "form"),
    ("comma_basis", "vectors", "commas", "form"),
)
FORM_CHOOSER_ROWS = frozenset(row for _, row, _, _ in FORM_CHOOSERS)

MNEMONICS = {
    ("ss_projection", "ssprimes"): "projection",
    ("ss_vectors", "primes"): "basis",
    ("vectors", "primes"): "mapping",
    ("mapping", "gens"): "mapped",
    ("mapping", "detempering"): "mapped",
    ("canon", "primes"): "mapping",
    ("canon", "gens"): "form",
    ("mapping", "canongens"): "form",
    ("canon", "detempering"): "mapped",
    ("canon", "commas"): "mapped",
    ("canon", "held"): "mapped",
    ("ss_mapping", "ssprimes"): "mapping",
    ("ss_vectors", "ssprimes"): "mapping",
    ("tuning", "ssgens"): "generator",
    ("tuning", "ssprimes"): "tuning",
    ("just", "ssprimes"): "just",
    ("retune", "ssprimes"): "retuning",
    ("vectors", "commas"): "comma",
    ("vectors", "targets"): "target",
    ("vectors", "held"): "held",
    ("vectors", "detempering"): "detempering",
    ("mapping", "primes"): "mapping",
    ("tuning", "gens"): "generator",
    ("tuning", "primes"): "tuning",
    ("just", "primes"): "just",
    ("retune", "primes"): "retuning",
    ("retune", "targets"): "error",
    ("prescaling", "primes"): "x",
    ("prescaling", "ssprimes"): "x",
    ("complexity", "targets"): "complexity",
    ("weight", "targets"): "weight",
    ("damage", "targets"): "damage",
}

EQUIVALENCES = {
    ("ss_projection", "ssprimes"): f" = G{SUBSCRIPT_L}𝑀{SUBSCRIPT_L}",
    ("tuning", "ssprimes"): " = 𝒈L𝑀L",
    ("retune", "ssprimes"): " = 𝒕L − 𝒋L",
    ("ss_vectors", "ssprimes"): " = 𝐼",
    ("ss_vectors", "commas"): " = BLC",
    ("ss_vectors", "held"): " = BLH",
    ("ss_vectors", "targets"): " = BLT",
    ("ss_vectors", "detempering"): " = BLD",
    ("ss_mapping", "ssgens"): " = 𝐼",
    ("ss_mapping", "ssprimes"): " = null⁻¹(BL·null(𝑀))",
    ("ss_mapping", "primes"): " = 𝑀LBL",
    ("ss_mapping", "targets"): " = 𝑀ₛ→LT",
    ("mapping", "commas"): " = O",
    ("canon", "detempering"): " = 𝐹",
    ("canon", "commas"): " = O",
    ("canon", "targets"): f" = 𝑀{SUBSCRIPT_C}T",
    ("vectors", "primes"): " = 𝐼",
    ("mapping", "gens"): " = 𝐼",
    ("mapping", "detempering"): " = 𝐼",
    ("canon", "canongens"): " = 𝐼",
    ("mapping", "targets"): " = 𝑀T",
    ("projection", "primes"): " = G𝑀 = V·diag(𝝀)V⁻¹",
    ("projection", "gens"): " = U(𝑀U)⁻¹",
    ("projection", "held"): " = H",
    ("projection", "ssprimes"): f" = G{SUBSCRIPT_L}→ₛ𝑀{SUBSCRIPT_L}",
    ("tuning", "detempering"): " = 𝒈",
    ("tuning", "primes"): " = 𝒈𝑀",
    ("tuning", "targets"): " = 𝒕T",
    ("just", "targets"): " = 𝒋T",
    ("retune", "primes"): " = 𝒕 − 𝒋",
    ("retune", "targets"): " = 𝒓T",
    ("damage", "targets"): " = |𝐞|𝒘",
    ("tuning", "held"): " = 𝒋H",
    ("just", "held"): " = 𝒕H",
    ("retune", "held"): " = 𝟎",
}

ALL_INTERVAL_SYMBOLS = {("vectors", "targets"): "Tₚ"}
ALL_INTERVAL_CAPTIONS = {("vectors", "targets"): "prime proxy target interval list"}
ALL_INTERVAL_EQUIVALENCES = {("vectors", "targets"): " = 𝐼"}
ALL_INTERVAL_MNEMONICS = {("vectors", "targets"): ("prime", "proxy")}

FORM_SUBSCRIPT_ROWS = frozenset({"mapping"})
FORM_SUBSCRIPT_GENS = frozenset({("tuning", "gens"), ("projection", "gens")})
FORM_EQUIVALENCES = {
    ("mapping", "targets"):    f" = 𝑀{SUBSCRIPT_C}T",
    ("tuning", "detempering"): f" = 𝒈{SUBSCRIPT_C}",
    ("tuning", "primes"):      f" = 𝒈{SUBSCRIPT_C}𝑀{SUBSCRIPT_C}",
    ("projection", "primes"):  f" = G{SUBSCRIPT_C}𝑀{SUBSCRIPT_C} = V·diag(𝝀)V⁻¹",
    ("projection", "gens"):    f" = U(𝑀{SUBSCRIPT_C}U)⁻¹",
}

UNITS = {
    ("vectors", "commas"): "p",
    ("projection", "commas"): "p",
    ("projection", "primes"): "p/p",
    ("projection", "ssgens"): f"b/g{SUBSCRIPT_L}",
    ("projection", "ssprimes"): "b/p",
    ("projection", "gens"): "p/g",
    ("projection", "detempering"): "p",
    ("projection", "targets"): "p",
    ("projection", "held"): "p",
    ("projection", "interest"): "p",
    ("vectors", "targets"): "p",
    ("vectors", "held"): "p",
    ("vectors", "detempering"): "p",
    ("vectors", "interest"): "p",
    ("ss_vectors", "ssprimes"): "p/p",
    ("vectors", "primes"): "p/p",
    ("canon", "primes"): f"g{SUBSCRIPT_C}/p",
    ("canon", "gens"): f"g{SUBSCRIPT_C}/g",
    ("canon", "canongens"): f"g{SUBSCRIPT_C}/g{SUBSCRIPT_C}",
    ("mapping", "canongens"): f"g/g{SUBSCRIPT_C}",
    ("projection", "canongens"): f"p/g{SUBSCRIPT_C}",
    ("tuning", "canongens"): f"¢/g{SUBSCRIPT_C}",
    ("mapping", "gens"): "g/g",
    ("mapping", "detempering"): "g",
    ("ss_vectors", "primes"): "p/b",
    ("ss_vectors", "commas"): "p",
    ("ss_vectors", "held"): "p",
    ("ss_vectors", "targets"): "p",
    ("ss_vectors", "interest"): "p",
    ("ss_vectors", "detempering"): "p",
    ("ss_mapping", "ssgens"): f"g{SUBSCRIPT_L}/g{SUBSCRIPT_L}",
    ("ss_mapping", "ssprimes"): f"g{SUBSCRIPT_L}/p",
    ("ss_mapping", "primes"): f"g{SUBSCRIPT_L}/b",
    ("ss_mapping", "commas"): f"g{SUBSCRIPT_L}",
    ("ss_mapping", "held"): f"g{SUBSCRIPT_L}",
    ("ss_mapping", "targets"): f"g{SUBSCRIPT_L}",
    ("ss_mapping", "interest"): f"g{SUBSCRIPT_L}",
    ("ss_mapping", "detempering"): f"g{SUBSCRIPT_L}",
    ("ss_projection", "ssprimes"): "p/p",
    ("ss_projection", "ssgens"): f"p/g{SUBSCRIPT_L}",
    ("ss_projection", "primes"): "p/b",
    ("ss_projection", "detempering"): "p",
    ("ss_projection", "commas"): "p",
    ("ss_projection", "targets"): "p",
    ("ss_projection", "held"): "p",
    ("ss_projection", "interest"): "p",
    ("tuning", "ssgens"): f"¢/g{SUBSCRIPT_L}",
    ("tuning", "ssprimes"): "¢/p",
    ("just", "ssprimes"): "¢/p",
    ("retune", "ssprimes"): "¢/p",
    ("mapping", "primes"): "g/p",
    ("mapping", "commas"): "g",
    ("mapping", "targets"): "g",
    ("mapping", "interest"): "g",
    ("canon", "primes"): f"g{SUBSCRIPT_C}/p",
    ("canon", "gens"): f"g{SUBSCRIPT_C}/g",
    ("canon", "detempering"): f"g{SUBSCRIPT_C}",
    ("canon", "commas"): f"g{SUBSCRIPT_C}",
    ("canon", "held"): f"g{SUBSCRIPT_C}",
    ("canon", "targets"): f"g{SUBSCRIPT_C}",
    ("canon", "interest"): f"g{SUBSCRIPT_C}",
    ("tuning", "gens"): "¢/g",
    ("tuning", "primes"): "¢/p",
    ("tuning", "commas"): "¢",
    ("tuning", "detempering"): "¢",
    ("tuning", "targets"): "¢",
    ("tuning", "interest"): "¢",
    ("just", "primes"): "¢/p",
    ("just", "commas"): "¢",
    ("just", "detempering"): "¢",
    ("just", "targets"): "¢",
    ("just", "interest"): "¢",
    ("retune", "primes"): "¢/p",
    ("retune", "commas"): "¢",
    ("retune", "detempering"): "¢",
    ("retune", "targets"): "¢",
    ("retune", "interest"): "¢",
    ("damage", "targets"): "¢",
    ("prescaling", "primes"): "oct/p",
    ("prescaling", "ssprimes"): "oct/p",
    ("prescaling", "commas"): "oct",
    ("prescaling", "detempering"): "oct",
    ("prescaling", "targets"): "oct",
    ("prescaling", "interest"): "oct",
    ("complexity", "primes"): "(C)/p",
    ("complexity", "ssprimes"): "(C)/p",
    ("complexity", "commas"): "(C)",
    ("complexity", "detempering"): "(C)",
    ("complexity", "targets"): "(C)",
    ("complexity", "interest"): "(C)",
    ("weight", "targets"): "(C)",
    ("mapping", "held"): "g",
    ("tuning", "held"): "¢",
    ("just", "held"): "¢",
    ("retune", "held"): "¢",
    ("prescaling", "held"): "oct",
    ("complexity", "held"): "(C)",
}
UNITED_ROWS = frozenset(row for row, _ in UNITS)

WEIGHT_EQUIVALENCE_BY_SLOPE = {
    "complexityWeight": " = 𝒄",
    "unityWeight": " = 𝟏",
    "simplicityWeight": " = 𝒄⁻¹",
}

PRESCALER_LETTER = {"log-prime": "𝐿", "prime": "diag(𝒑)", "identity": "𝐼"}

TILES = (
    ("block:qgens", "quantities", "gens"),
    ("block:primes", "quantities", "primes"),
    ("block:commas", "quantities", "commas"),
    ("block:targets", "quantities", "targets"),
    ("block:vec:quantities", "vectors", "quantities"),
    ("block:vec:commas", "vectors", "commas"),
    ("block:vec:targets", "vectors", "targets"),
    ("block:cangens", "quantities", "canongens"),
    ("block:canonspine", "canon", "quantities"),
    ("block:form", "canon", "gens"),
    ("block:fcancel", "canon", "canongens"),
    ("block:finv", "mapping", "canongens"),
    ("block:embed_c", "projection", "canongens"),
    ("block:tuning:canongens", "tuning", "canongens"),
    ("block:canon", "canon", "primes"),
    ("block:gens", "mapping", "quantities"),
    ("block:mapping", "mapping", "primes"),
    ("block:vec:primes", "vectors", "primes"),
    ("block:selfmap", "mapping", "gens"),
    ("block:projection", "projection", "primes"),
    ("block:projection_embedding", "projection", "gens"),
    ("block:proj_v", "projection", "commas"),
    ("block:scaling_factors", "scaling_factors", "commas"),
    ("block:mapped_comma", "mapping", "commas"),
    ("block:mapped", "mapping", "targets"),
    ("block:tuning:gens", "tuning", "gens"),
    ("block:tuning:primes", "tuning", "primes"),
    ("block:tuning:commas", "tuning", "commas"),
    ("block:tuning:targets", "tuning", "targets"),
    ("block:just:primes", "just", "primes"),
    ("block:just:commas", "just", "commas"),
    ("block:just:targets", "just", "targets"),
    ("block:retune:primes", "retune", "primes"),
    ("block:retune:commas", "retune", "commas"),
    ("block:retune:targets", "retune", "targets"),
    ("block:prescaling:primes", "prescaling", "primes"),
    ("block:prescaling:commas", "prescaling", "commas"),
    ("block:prescaling:targets", "prescaling", "targets"),
    ("block:complexity:primes", "complexity", "primes"),
    ("block:complexity:commas", "complexity", "commas"),
    ("block:complexity:targets", "complexity", "targets"),
    ("block:weight:targets", "weight", "targets"),
    ("block:damage:targets", "damage", "targets"),
)

SUPERSPACE_TILES = (
    ("block:ss_quantities:ssgens", "quantities", "ssgens"),
    ("block:ss_quantities:ssprimes", "quantities", "ssprimes"),
    ("block:ss_vectors:quantities", "ss_vectors", "quantities"),
    ("block:ss_vectors:ssprimes", "ss_vectors", "ssprimes"),
    ("block:ss_vectors:primes", "ss_vectors", "primes"),
    ("block:ss_vectors:commas", "ss_vectors", "commas"),
    ("block:ss_vectors:held", "ss_vectors", "held"),
    ("block:ss_vectors:targets", "ss_vectors", "targets"),
    ("block:ss_vectors:interest", "ss_vectors", "interest"),
    ("block:ss_vectors:detempering", "ss_vectors", "detempering"),
    ("block:ss_mapping:quantities", "ss_mapping", "quantities"),
    ("block:ss_mapping:ssgens", "ss_mapping", "ssgens"),
    ("block:ss_mapping:ssprimes", "ss_mapping", "ssprimes"),
    ("block:ss_mapping:primes", "ss_mapping", "primes"),
    ("block:ss_mapping:commas", "ss_mapping", "commas"),
    ("block:ss_mapping:held", "ss_mapping", "held"),
    ("block:ss_mapping:targets", "ss_mapping", "targets"),
    ("block:ss_mapping:interest", "ss_mapping", "interest"),
    ("block:ss_mapping:detempering", "ss_mapping", "detempering"),
    ("block:ss_projection:ssprimes", "ss_projection", "ssprimes"),
    ("block:ss_projection:quantities", "ss_projection", "quantities"),
    ("block:tuning:ssgens", "tuning", "ssgens"),
    ("block:tuning:ssprimes", "tuning", "ssprimes"),
    ("block:just:ssprimes", "just", "ssprimes"),
    ("block:retune:ssprimes", "retune", "ssprimes"),
    ("block:prescaling:ssprimes", "prescaling", "ssprimes"),
    ("block:complexity:ssprimes", "complexity", "ssprimes"),
)


UNITS_TILES = (
    ("block:ucol:vectors", "vectors", "units"),
    ("block:ucol:canon", "canon", "units"),
    ("block:ucol:mapping", "mapping", "units"),
    ("block:ucol:tuning", "tuning", "units"),
    ("block:ucol:just", "just", "units"),
    ("block:ucol:retune", "retune", "units"),
    ("block:ucol:prescaling", "prescaling", "units"),
    ("block:ucol:complexity", "complexity", "units"),
    ("block:ucol:weight", "weight", "units"),
    ("block:ucol:damage", "damage", "units"),
    ("block:urow:canongens", "units", "canongens"),
    ("block:urow:gens", "units", "gens"),
    ("block:urow:primes", "units", "primes"),
    ("block:urow:commas", "units", "commas"),
    ("block:urow:targets", "units", "targets"),
    ("block:ucol:ss_vectors", "ss_vectors", "units"),
    ("block:ucol:ss_mapping", "ss_mapping", "units"),
    ("block:ucol:ss_projection", "ss_projection", "units"),
    ("block:urow:ssgens", "units", "ssgens"),
    ("block:urow:ssprimes", "units", "ssprimes"),
)

EDITABLE_PTEXT = frozenset({("mapping", "primes"), ("vectors", "commas"), ("tuning", "gens"),
                            ("vectors", "targets"), ("prescaling", "primes"),
                            ("mapping", "canongens"),
                            ("projection", "primes"), ("projection", "gens")})
EDITABLE_PTEXT_ROWS = frozenset(r for r, _ in EDITABLE_PTEXT)
PTEXT_ROWS = frozenset({"quantities", "vectors", "mapping", "canon", "tuning", "just", "retune", "damage",
                        "prescaling", "complexity", "weight",
                        "projection", "scaling_factors",
                        "ss_vectors", "ss_mapping", "ss_projection"})

GRIDDED_KINDS = frozenset({
    "prime", "ratiocell", "commaratio", "genratio", "mapping", "mapped", "commacell",
    "vec", "tuningvalue", "mathexpr", "interestcell", "formcell", "heldcell", "gentuningcell", "targetcell",
    "prescalercell",
    "elementcell", "elementratio", "unchangedcell",
    "bracket", "ebktop", "ebkbrace", "ebkangle", "transpose", "vbar", "matlabel",
    "minus", "plus", "gen_minus", "gen_plus", "map_minus", "map_plus", "comma_minus", "comma_plus", "basis_minus",
    "element_minus", "element_plus",
    "interest_minus", "interest_plus", "held_minus", "held_plus", "target_minus", "target_plus",
    "colgrip",
    "boxtitle", "powerinput", "powerdisplay",
})
BLANKED_NUMBER_KINDS = frozenset({
    "genratio", "mapping", "mapped", "commacell", "vec", "tuningvalue", "interestcell", "formcell", "heldcell",
    "gentuningcell", "targetcell", "prescalercell",
    "prime", "elementcell", "elementratio", "ratiocell", "commaratio", "unchangedcell",
})

RINGABLE_KINDS = BLANKED_NUMBER_KINDS | frozenset({
    "mathexpr", "powerdisplay",
})
