from __future__ import annotations

from rtt.app.marks import BR_INSET, BR_SERIF_L

VALUE_KINDS: frozenset[str] = frozenset(
    {
        "prime",
        "formcell",
        "mapped",
        "vector",
        "tuningvalue",
        "genratio",
        "commaratio",
        "powerdisplay",
        "mathexpr",
        "mapping",
        "commacell",
        "unchangedcell",
        "interestcell",
        "heldcell",
        "targetcell",
        "prescalercell",
        "weightcell",
        "powerinput",
        "gentuningcell",
        "ratiocell",
        "elementcell",
        "elementratio",
    }
)

ROW_HEIGHT = 37
COLUMN_WIDTH = 37
GAP = 28
PAD = 4
TITLE_MARGIN = 8
WASH_PAD = GAP / 2
LABEL_WIDTH = 106
HEADER_HEIGHT = 36
STRIP = 16
TOGGLE = 12
BUTTON = TOGGLE
GRIP_BAND = 16
TOGGLE_INSET = 3
CAPTION_FONT = 9
CAPTION_LINE = 10
CAPTION_CHAR_WIDTH = 0.52
MAX_CAPTION_LINES = 2
PRESET_HEIGHT = 30
LBOX_DIM_WIDTH = 80
CBOX_DROP_WIDTH = 170
CBOX_SLOT_WIDTH = 60
CBOX_NODROP_WIDTH = CBOX_SLOT_WIDTH + 8 + CBOX_SLOT_WIDTH
CBOX_WIDTH = CBOX_DROP_WIDTH + 8 + CBOX_NODROP_WIDTH
OPTION_BOX_PX = 16
PRESET_WIDTH = 124
SCHEME_BUTTON_SQ = 22
SCHEME_LABEL_WIDTH = 92
SCHEME_CTRL_WIDTH = SCHEME_BUTTON_SQ + 2 + SCHEME_LABEL_WIDTH
TARGET_PRESET_WIDTH = 144
PLAIN_TEXT_MAX_FONT = 10
PLAIN_TEXT_HEIGHT = 13
PLAIN_TEXT_EDIT_HEIGHT = 16
SYMBOL_HEIGHT = 18
BAND_GAP = 6
SYMBOL_FONT = 15
MATLABEL_HEIGHT = 13
MATLABEL_PAD = 4
MATLABEL_WIDTH = 22
MATLABEL_W_SS = 64
MATLABEL_W_SSPRIMES = 56
UNIT_HEIGHT = 12
CHART_HEIGHT = 64
CHART_GAP = 4
RANGE_CHART_HEIGHT = 58
RANGE_MODE_HEIGHT = 46
RANGE_GAP = 2
OPT_TITLE_HEIGHT = 14
OPT_PAD_T = 8
OPT_PAD_B = 8
OPT_PAD_L = 8
OPT_PAD_R = 8
OPT_TITLE_GAP = 4
OPT_COL_GAP = 8
OPT_POW_CAP_WIDTH = 90
OPT_MEAN_DAMAGE_WIDTH = 64
OPT_BOX_MIN_WIDTH = OPT_PAD_L + OPT_MEAN_DAMAGE_WIDTH + OPT_COL_GAP + OPT_POW_CAP_WIDTH + OPT_PAD_R
BOX_OUTER = 4
BOX_INNER = 8
TBOX_WIDTH = 2 * BOX_OUTER + 2 * BOX_INNER + TARGET_PRESET_WIDTH + 8 + LBOX_DIM_WIDTH
PBOX_WIDTH = 2 * BOX_OUTER + 2 * BOX_INNER + PRESET_WIDTH + 8 + LBOX_DIM_WIDTH
BOX_TITLE_HEIGHT = 14
BOX_TITLE_GAP = 4
APPROACH_RADIO_HEIGHT = 64
FRAME_HEIGHT = 9
BRACE_HEIGHT = 7
FRAME_GAP = 5
BRACKET_WIDTH = 16
FRAME_OVERHANG = BRACKET_WIDTH - BR_INSET - BR_SERIF_L
ROW_HANDLE_WIDTH = 14
ROW_HANDLE_GAP = 4
ETPICK_WIDTH = COLUMN_WIDTH
ETPICK_GAP = 4
COMMAPICK_GAP = 4
VAL_BRACKET_HEIGHT = 16
TRANSPOSE_WIDTH = 9
MARK_INSET = 8
SEP_WIDTH = 2
V_SPLIT_GAP = 16
INTERVAL_COL_GAP = V_SPLIT_GAP
LINE_WIDTH = 2
MAP_BRACKETS = ("⟨", "]")
LIST_BRACKETS = ("[", "]")
GENMAP_BRACKETS = ("{", "]")
DASH = "—"
