from __future__ import annotations

from rtt.app.grid_tables import (
    ALL_INTERVAL_CAPTIONS,
    ALL_INTERVAL_EQUIVALENCES,
    ALL_INTERVAL_MNEMONICS,
    ALL_INTERVAL_SYMBOLS,
    BLANKED_NUMBER_KINDS,
    CAPTIONED_ROWS,
    CAPTIONS,
    CELL_FACTORS,
    CHARTED_ROWS,
    COL_LABEL_LETTERS,
    COL_LABELED_ROWS,
    COUNTS,
    COUNTS_TILES,
    DETEMPERING_COUNTS,
    DETEMPERING_COUNTS_TILES,
    EDITABLE_PTEXT,
    EDITABLE_PTEXT_ROWS,
    EQUIVALENCES,
    FORM_CHOOSER_ROWS,
    FORM_CHOOSERS,
    FORM_EQUIVALENCES,
    FORM_SUBSCRIPT_GENS,
    FORM_SUBSCRIPT_ROWS,
    FRAMED_ROWS,
    GRIDDED_KINDS,
    MNEMONICS,
    NORM_SUB_CLOSE,
    NORM_SUB_OPEN,
    OPTIMIZATION_COUNTS,
    OPTIMIZATION_COUNTS_TILES,
    PRESCALER_LETTER,
    PRESET_COPIES,
    PRESET_ROWS,
    PRESETS,
    RINGABLE_KINDS,
    ROW_LABEL_LETTERS,
    SPINE_COLUMN_GROUP,
    SPINE_COLUMNS,
    SPINE_ROW_GROUP,
    SPINE_ROWS,
    SUB_CLOSE,
    SUB_OPEN,
    SUBSCRIPT_C,
    SUBSCRIPT_L,
    SUPERSPACE_COUNTS,
    SUPERSPACE_COUNTS_TILES,
    SUPERSPACE_REGION_COLUMNS,
    SUPERSPACE_REGION_ROWS,
    SUPERSPACE_TILES,
    SYMBOLED_ROWS,
    SYMBOLS,
    TILES,
    UNITED_ROWS,
    UNITS,
    UNITS_TILES,
    WEIGHT_EQUIVALENCE_BY_SLOPE,
)
from rtt.app.layout import Block, CellBox, Layout, Line
from rtt.app.spreadsheet_brackets import _BracketsMixin
from rtt.app.spreadsheet_constants import (
    APPROACH_RADIO_H,
    BAND_GAP,
    BOX_INNER,
    BOX_OUTER,
    BOX_TITLE_GAP,
    BOX_TITLE_H,
    BRACE_H,
    BRACKET_W,
    BTN,
    CAPTION_CHAR_W,
    CAPTION_FONT,
    CAPTION_LINE,
    CBOX_DROP_W,
    CBOX_NODROP_W,
    CBOX_SLOT_W,
    CBOX_W,
    CHART_GAP,
    CHART_H,
    COL_W,
    COMMAPICK_GAP,
    CTRL_LABEL_GAP,
    DASH,
    ETPICK_GAP,
    ETPICK_W,
    FRAME_GAP,
    FRAME_H,
    FRAME_OVERHANG,
    GAP,
    GENMAP_BRACKETS,
    GRIP_BAND,
    HEADER_H,
    KET_INSET,
    LABEL_W,
    LBOX_DIM_W,
    LINE_W,
    LIST_BRACKETS,
    MAP_BRACKETS,
    MARK_INSET,
    MATLABEL_H,
    MATLABEL_PAD,
    MATLABEL_W,
    MATLABEL_W_SS,
    MATLABEL_W_SSPRIMES,
    MAX_CAPTION_LINES,
    OPT_BOX_MIN_W,
    OPT_COL_GAP,
    OPT_MEAN_DAMAGE_W,
    OPT_PAD_B,
    OPT_PAD_L,
    OPT_PAD_R,
    OPT_PAD_T,
    OPT_POW_CAP_W,
    OPT_TITLE_GAP,
    OPT_TITLE_H,
    OPTION_BOX_PX,
    PAD,
    PBOX_W,
    PRESET_H,
    PRESET_W,
    PTEXT_EDIT_H,
    PTEXT_H,
    PTEXT_MAX_FONT,
    RANGE_CHART_H,
    RANGE_GAP,
    RANGE_MODE_H,
    ROW_H,
    ROW_HANDLE_GAP,
    ROW_HANDLE_W,
    SCHEME_BTN_SQ,
    SCHEME_CTRL_W,
    SCHEME_LABEL_W,
    SEP_W,
    STRIP,
    SYMBOL_FONT,
    SYMBOL_H,
    TARGET_PRESET_W,
    TBOX_W,
    TITLE_MARGIN,
    TOGGLE,
    TOGGLE_INSET,
    TRANSPOSE_W,
    UNIT_H,
    V_SPLIT_GAP,
    VAL_BRACKET_H,
    WASH_PAD,
)
from rtt.app.spreadsheet_controls import _ControlsMixin
from rtt.app.spreadsheet_decorations import _DecorationsMixin
from rtt.app.spreadsheet_emit_matrix import _EmitMatrixMixin
from rtt.app.spreadsheet_emit_tuning import _EmitTuningMixin
from rtt.app.spreadsheet_emit_vectors import _EmitVectorsMixin
from rtt.app.spreadsheet_geometry import _GeometryMixin
from rtt.app.spreadsheet_layout import _LayoutMixin
from rtt.app.spreadsheet_models import (
    _resolve_prescaler_labels,
    _resolve_show_flags,
)
from rtt.app.spreadsheet_resolve import _ResolveMixin
from rtt.app.spreadsheet_text import (
    _cell_content,
    _log_operand,
    _math_expr,
    _min_width_for_lines,
    _sub,
    _title_w,
    _wrap_lines,
    assign_column_tokens,
    changed_cell_ids,
    pending_token,
    removed_cell_ids,
    toggle_all_collapsed,
)

__all__ = [
    "ALL_INTERVAL_CAPTIONS",
    "ALL_INTERVAL_EQUIVALENCES",
    "ALL_INTERVAL_MNEMONICS",
    "ALL_INTERVAL_SYMBOLS",
    "APPROACH_RADIO_H",
    "BAND_GAP",
    "BLANKED_NUMBER_KINDS",
    "BOX_INNER",
    "BOX_OUTER",
    "BOX_TITLE_GAP",
    "BOX_TITLE_H",
    "BRACE_H",
    "BRACKET_W",
    "BTN",
    "CAPTIONED_ROWS",
    "CAPTIONS",
    "CAPTION_CHAR_W",
    "CAPTION_FONT",
    "CAPTION_LINE",
    "CBOX_DROP_W",
    "CBOX_NODROP_W",
    "CBOX_SLOT_W",
    "CBOX_W",
    "CELL_FACTORS",
    "CHARTED_ROWS",
    "CHART_GAP",
    "CHART_H",
    "COL_LABELED_ROWS",
    "COL_LABEL_LETTERS",
    "COL_W",
    "COMMAPICK_GAP",
    "COUNTS",
    "COUNTS_TILES",
    "CTRL_LABEL_GAP",
    "DASH",
    "DETEMPERING_COUNTS",
    "DETEMPERING_COUNTS_TILES",
    "EDITABLE_PTEXT",
    "EDITABLE_PTEXT_ROWS",
    "EQUIVALENCES",
    "ETPICK_GAP",
    "ETPICK_W",
    "FORM_CHOOSERS",
    "FORM_CHOOSER_ROWS",
    "FORM_EQUIVALENCES",
    "FORM_SUBSCRIPT_GENS",
    "FORM_SUBSCRIPT_ROWS",
    "FRAMED_ROWS",
    "FRAME_GAP",
    "FRAME_H",
    "FRAME_OVERHANG",
    "GAP",
    "GENMAP_BRACKETS",
    "GRIDDED_KINDS",
    "GRIP_BAND",
    "HEADER_H",
    "KET_INSET",
    "LABEL_W",
    "LBOX_DIM_W",
    "LINE_W",
    "LIST_BRACKETS",
    "MAP_BRACKETS",
    "MARK_INSET",
    "MATLABEL_H",
    "MATLABEL_PAD",
    "MATLABEL_W",
    "MATLABEL_W_SS",
    "MATLABEL_W_SSPRIMES",
    "MAX_CAPTION_LINES",
    "MNEMONICS",
    "NORM_SUB_CLOSE",
    "NORM_SUB_OPEN",
    "OPTIMIZATION_COUNTS",
    "OPTIMIZATION_COUNTS_TILES",
    "OPTION_BOX_PX",
    "OPT_BOX_MIN_W",
    "OPT_COL_GAP",
    "OPT_MEAN_DAMAGE_W",
    "OPT_PAD_B",
    "OPT_PAD_L",
    "OPT_PAD_R",
    "OPT_PAD_T",
    "OPT_POW_CAP_W",
    "OPT_TITLE_GAP",
    "OPT_TITLE_H",
    "PAD",
    "PBOX_W",
    "PRESCALER_LETTER",
    "PRESETS",
    "PRESET_COPIES",
    "PRESET_H",
    "PRESET_ROWS",
    "PRESET_W",
    "PTEXT_EDIT_H",
    "PTEXT_H",
    "PTEXT_MAX_FONT",
    "RANGE_CHART_H",
    "RANGE_GAP",
    "RANGE_MODE_H",
    "RINGABLE_KINDS",
    "ROW_H",
    "ROW_HANDLE_GAP",
    "ROW_HANDLE_W",
    "ROW_LABEL_LETTERS",
    "SCHEME_BTN_SQ",
    "SCHEME_CTRL_W",
    "SCHEME_LABEL_W",
    "SEP_W",
    "SPINE_COLUMNS",
    "SPINE_COLUMN_GROUP",
    "SPINE_ROWS",
    "SPINE_ROW_GROUP",
    "STRIP",
    "SUBSCRIPT_C",
    "SUBSCRIPT_L",
    "SUB_CLOSE",
    "SUB_OPEN",
    "SUPERSPACE_COUNTS",
    "SUPERSPACE_COUNTS_TILES",
    "SUPERSPACE_REGION_COLUMNS",
    "SUPERSPACE_REGION_ROWS",
    "SUPERSPACE_TILES",
    "SYMBOLED_ROWS",
    "SYMBOLS",
    "SYMBOL_FONT",
    "SYMBOL_H",
    "TARGET_PRESET_W",
    "TBOX_W",
    "TILES",
    "TITLE_MARGIN",
    "TOGGLE",
    "TOGGLE_INSET",
    "TRANSPOSE_W",
    "UNITED_ROWS",
    "UNITS",
    "UNITS_TILES",
    "UNIT_H",
    "VAL_BRACKET_H",
    "V_SPLIT_GAP",
    "WASH_PAD",
    "WEIGHT_EQUIVALENCE_BY_SLOPE",
    "_GridBuilder",
    "_cell_content",
    "_log_operand",
    "_math_expr",
    "_min_width_for_lines",
    "_resolve_prescaler_labels",
    "_resolve_show_flags",
    "_sub",
    "_title_w",
    "_wrap_lines",
    "assign_column_tokens",
    "build",
    "changed_cell_ids",
    "pending_token",
    "removed_cell_ids",
    "toggle_all_collapsed",
]


class _GridBuilder(
    _ResolveMixin,
    _LayoutMixin,
    _GeometryMixin,
    _EmitMatrixMixin,
    _EmitVectorsMixin,
    _EmitTuningMixin,
    _ControlsMixin,
    _BracketsMixin,
    _DecorationsMixin,
):
    def layout(self) -> Layout:
        self.cells: list[CellBox] = []
        self.lines: list[Line] = []
        self.blocks: list[Block] = []
        self._control_region_boxes: list[Block] = []

        self._emit_headers()
        self._emit_counts_row()
        self._emit_units()
        self._emit_quantities_row()
        self._emit_column_plus_controls()
        self._emit_rehomed_minus_controls()
        self._emit_mapping_band()
        self._emit_projection_band()
        self._emit_canon_band()
        self._emit_vectors_band()
        self._emit_superspace_rows()
        self._emit_identity_objects()
        chart_indicators = self._emit_tuning_rows()
        self._emit_prescaling_band()
        self._emit_lbox_control()
        self._emit_cbox_controls()
        self._emit_complexity_row()
        self._emit_weight_row()
        self._emit_damage_row(chart_indicators)
        self._emit_charts(chart_indicators)
        gtm_box = self._emit_tuning_ranges_box()
        opt_box = self._emit_optimization_box()
        approach_frame = self._emit_approach_box()
        self._emit_brackets()
        self._emit_matrix_labels()
        self._emit_axes()
        self._emit_panels(gtm_box, opt_box, approach_frame)
        self._emit_washes()
        self._emit_symbols_captions()
        self._emit_presets()
        self._emit_all_interval_check_fallback()
        self._emit_form_choosers()
        self._emit_scheme_buttons()
        self._emit_ptext_band()
        self._emit_ebk_frames_and_marks()
        self._emit_tile_toggles()
        self._apply_value_display_filters()

        title_right = max((c.x + c.w / 2 + _title_w(c.text) / 2 for c in self.cells if c.kind == "colheader"),
                          default=self.total_w)
        right_overhang = max(0.0, title_right - self.total_w)

        return Layout(self.total_w, self.total_h, tuple(self.lines), tuple(self.blocks), tuple(self.cells),
                      freeze_x=self.node_edge + GAP - PAD, freeze_y=self.branch_top_y + GAP + GRIP_BAND - PAD,
                      right_overhang=right_overhang, identities=self._col_ids,
                      approach_box=self.approach_box)


def build(state, settings=None, collapsed=None, **inputs) -> Layout:
    return _GridBuilder(state, settings=settings, collapsed=collapsed, **inputs).layout()
