from __future__ import annotations

from rtt.app.marks import BR_INSET, BR_SERIF_L

VALUE_KINDS: frozenset[str] = frozenset(
    {
        "prime",
        "form_cell",
        "mapped",
        "vector",
        "tuning_value",
        "generator_ratio",
        "comma_ratio",
        "power_display",
        "math_expression",
        "mapping",
        "comma_cell",
        "unchanged_cell",
        "interest_cell",
        "held_cell",
        "target_cell",
        "prescaler_cell",
        "weight_cell",
        "power_input",
        "generator_tuning_cell",
        "ratio_cell",
        "element_cell",
        "element_ratio",
    }
)

ROW_HEIGHT = 37
COLUMN_WIDTH = 37
GAP = 28
PAD = 4
TITLE_MARGIN = 8
WASH_PADDING = GAP / 2
LABEL_WIDTH = 106
HEADER_HEIGHT = 36
STRIP = 16
TOGGLE = 12
BUTTON = TOGGLE
GRIP_BAND = 16
TOGGLE_INSET = 3
CAPTION_FONT = 9
CAPTION_LINE = 10
MAX_CAPTION_LINES = 2
PRESET_HEIGHT = 30
BOX_GAP = 8
PRESCALING_BOX_DIM_WIDTH = 80
COMPLEXITY_BOX_DROP_WIDTH = 170
COMPLEXITY_BOX_SLOT_WIDTH = 60
COMPLEXITY_BOX_NODROP_WIDTH = COMPLEXITY_BOX_SLOT_WIDTH + BOX_GAP + COMPLEXITY_BOX_SLOT_WIDTH
COMPLEXITY_BOX_WIDTH = COMPLEXITY_BOX_DROP_WIDTH + BOX_GAP + COMPLEXITY_BOX_NODROP_WIDTH
OPTION_BOX_PX = 16
PRESET_WIDTH = 124
SCHEME_BUTTON_SQ = 22
SCHEME_LABEL_WIDTH = 92
SCHEME_CONTROL_WIDTH = SCHEME_BUTTON_SQ + 2 + SCHEME_LABEL_WIDTH
TARGET_PRESET_WIDTH = 144
PLAIN_TEXT_MAX_FONT = 10
PLAIN_TEXT_HEIGHT = 13
PLAIN_TEXT_EDIT_HEIGHT = 16
SYMBOL_HEIGHT = 18
BAND_GAP = 6
SYMBOL_FONT = 15
CELL_FONT = 17
STACKED_MAIN_FONT = 10
STACKED_SUB_FONT = 7
RANGE_FONT = 7
SUB_FONT_PCT = 70
MATRIX_LABEL_HEIGHT = 13
MATRIX_LABEL_PADDING = 4
MATRIX_LABEL_WIDTH = 22
MATRIX_LABEL_SUPERSPACE_WIDTH = 64
MATRIX_LABEL_SUPERSPACE_PRIMES_WIDTH = 56
UNIT_HEIGHT = 12
CHART_HEIGHT = 64
CHART_GAP = 4
RANGE_CHART_HEIGHT = 58
RANGE_MODE_HEIGHT = 46
RANGE_GAP = 2
OPTIMIZATION_TITLE_HEIGHT = 14
OPTIMIZATION_PADDING = 8
OPTIMIZATION_PADDING_T = OPTIMIZATION_PADDING_B = OPTIMIZATION_PADDING_L = (
    OPTIMIZATION_PADDING_R
) = OPTIMIZATION_PADDING
OPTIMIZATION_TITLE_GAP = 4
OPTIMIZATION_COL_GAP = 8
OPTIMIZATION_POWER_CAP_WIDTH = 90
OPTIMIZATION_MEAN_DAMAGE_WIDTH = 64
OPTIMIZATION_BOX_MIN_WIDTH = (
    OPTIMIZATION_PADDING_L
    + OPTIMIZATION_MEAN_DAMAGE_WIDTH
    + OPTIMIZATION_COL_GAP
    + OPTIMIZATION_POWER_CAP_WIDTH
    + OPTIMIZATION_PADDING_R
)
BOX_OUTER = 4
BOX_INNER = 8
TARGET_BOX_WIDTH = (
    2 * BOX_OUTER + 2 * BOX_INNER + TARGET_PRESET_WIDTH + BOX_GAP + PRESCALING_BOX_DIM_WIDTH
)
PRESET_BOX_WIDTH = 2 * BOX_OUTER + 2 * BOX_INNER + PRESET_WIDTH + BOX_GAP + PRESCALING_BOX_DIM_WIDTH
BOX_TITLE_HEIGHT = 14
BOX_TITLE_GAP = 4
APPROACH_RADIO_HEIGHT = 64
FRAME_HEIGHT = 9
BRACE_HEIGHT = 7
FRAME_GAP = 5
BRACKET_WIDTH = 16
FRAME_OVERHANG = BRACKET_WIDTH - BR_INSET - BR_SERIF_L
ROW_HANDLE_WIDTH = 14
ROW_HANDLE_GAP = 4
ETPICK_WIDTH = COLUMN_WIDTH
ETPICK_GAP = 4
COMMAPICK_GAP = 4
VAL_BRACKET_HEIGHT = 16
TRANSPOSE_WIDTH = 9
MARK_INSET = 8
SEP_WIDTH = 2
V_SPLIT_GAP = 16
INTERVAL_COL_GAP = V_SPLIT_GAP
LINE_WIDTH = 2
DASH = "—"
